INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AYJAY SERVICES','AJA','A J Services',17),
	 ('BAIR','ABP','Aba Air',9),
	 ('ABAKAN-AVIA','ABG','Abakan-Avia',43),
	 ('ABAS','MRP','Abas',9),
	 ('ABC HUNGARY','AHU','ABC Air Hungary',22),
	 ('FLY TYROL','FTY','ABC Bedarsflug',3),
	 ('ABG','AAB','Abelag Aviation',5),
	 ('SKY CHALLENGER','CHG','AC Challenge Aero',48),
	 (NULL,'IAE','AC Insat-Aero',43),
	 ('ACEF','CFM','ACEF',40);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('BAVARIAN','BVR','ACM Air Charter',10),
	 ('AVIATION SERVICE','ORS','Action Air',26),
	 ('AIR ROMANIA','RRM','Acvila Air-Romanian Carrier',41),
	 ('FLIGHTVUE','VUE','AD Aviation',17),
	 ('ADA AIR','ADE','Ada Air',2),
	 ('ADRIA','ADR','Adria Airways',45),
	 ('ADLINES','RDD','Adygeya Airlines',43),
	 ('AEGEAN','AEE','Aegean Airlines',20),
	 ('AER ARANN','REA','Aer Arann',23),
	 ('SHAMROCK','EIN','Aer Lingus',23);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AERTURAS','ATT','Aer Turas',23),
	 ('AEREA TRAINING','ADG','Aerea Flying Training Organization',13),
	 (NULL,'AXZ','Aereonautica militare',26),
	 ('FAST TRACK','FST','Aereos Limited',17),
	 ('AIR TARA','AGP','AERFI Group',23),
	 ('SKYWINGS','ABF','Aerial Oy',14),
	 ('AEREM','MBV','Aeriantur-M',33),
	 ('AERIS','RIS','Aeris Gestion',13),
	 ('AERMARCHE','MMC','Aermarche',26),
	 ('REVAL','EAY','Aero Airlines',12);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('ALBATROS ESPANA','ABM','Aero Albatros',13),
	 ('SKYBANNER','DSK','Aero Algarve',40),
	 ('GLOBAL JET','GBJ','Aero Business Charter',10),
	 ('KRIFKA AIR','KFK','Aero Charter Krifka',3),
	 ('CLUB PORTUGAL','CLP','Aero Club De Portugal',40),
	 ('CLUBE ALGARVE','CGV','Aero Clube Do Algarve',40),
	 ('COTSWOLD','ADL','Aero Dynamics',17),
	 ('AERO ENTERPRISE','AON','Aero Entreprise',16),
	 ('AERO FENIX','FNX','Aero Fenix',16),
	 ('Aero Fox','ARF','Aero Flight',10);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('LINK SERVICE','ARK','Aero Link Air Services S.L.',13),
	 (NULL,'AEF','Aero Lloyd (YP)',10),
	 ('AEROMADRID','AEM','Aero Madrid',13),
	 ('AERONOVA','OVA','Aero Nova',13),
	 ('AEROMASTER','NRO','Aero Rent JSC',43),
	 ('BIRD EXPRESS','BES','Aero Services Executive',16),
	 ('AERO NITRA','ASO','Aero Slovakia',46),
	 ('VALLES','VAD','Aero Taxi Los Valles',13),
	 ('AERO VILAMOURA','VMR','Aero Vilamoura',40),
	 ('AEROVISION','AOV','Aero Vision',16);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AERO CZECH','AOD','Aero Vodochody',9),
	 ('CHARTER UKRAINE','UCR','Aero-Charter Ukraine',48),
	 ('AERAFKAM','MSV','Aero-Kamov',43),
	 ('AERO-PYRENEES','EAP','Aero-Pyrenees',16),
	 (NULL,'LSM','Aerobusinessservice',43),
	 ('AEROCLUB FLAPS','FLP','Aeroclub Flaps',13),
	 ('AEROCONDOR','ARD','Aerocondor',40),
	 ('FLIGHT CHECKER','FII','Aerodata Flight Inspection',10),
	 ('AERODIENST','ADN','Aerodienst GmbH',10),
	 ('AEROMAN','MAM','Aerodromo De La Mancha',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AEROFAN','CFF','Aerofan',13),
	 ('AEROFLOT','AFL','Aeroflot Russian Airlines',43),
	 ('AEROFLOT-CARGO','RCF','Aeroflot-Cargo',43),
	 ('DONAVIA','DNV','Aeroflot-Don',43),
	 ('DVINA','AUL','Aeroflot-Nord',43),
	 ('RIAZOR','FNO','Aeroflota Del Noroeste',13),
	 (NULL,'FRT','Aerofreight Airlines',43),
	 ('TYNWALD','RWY','Aerogroup 98 Limited',17),
	 ('AEROITALIA','ROO','Aeroitalia',26),
	 ('NOVOKUZNETSK','NKZ','Aerokuzbass',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SYLT-AIR','AWU','Aeroline GmbH',10),
	 (NULL,'LDL','Aerologic',43),
	 ('AMEX','ARM','Aeromarket Express',13),
	 ('AEROMAX SPAIN','AXP','Aeromax',13),
	 ('LIFELINE','AMQ','Aeromedicare Ltd.',17),
	 ('OMEGA','OMG','Aeromega',17),
	 ('AEROMIST','AHW','Aeromist-Kharkiv',48),
	 ('AERO CASTELLANA','ECL','Aeronautica Castellana',13),
	 ('Italian Airforce','IAM','Aeronautica Militare',26),
	 ('DIANA','EVR','Aeronautical Academy of Europe',40);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AERONOR','ENW','Aeronaves Del Noroeste',13),
	 ('AERONAVIGACIYA','KTN','Aeronavigaciya',48),
	 ('AEROCARTO','GCF','Aeronor',13),
	 ('AERONORD','NRP','Aeronord-Grup',33),
	 ('LUZAVIA','RTE','Aeronorte',40),
	 ('AEROPILOTO','AOP','Aeropiloto',40),
	 (NULL,'PUT','Aeroput',42),
	 ('AEROM','AMM','Aeroputul International Marculesti',33),
	 ('BIRD JET','CJE','Aeroservices Corporate',16),
	 ('AEROSTAR','UAR','Aerostar Airlines',48);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AEROSVIT','AEW','Aerosvit Airlines',48),
	 ('AEROTAXI','ITE','Aerotaxi',9),
	 ('AEROTEC','AEP','Aerotec',13),
	 (NULL,'CDU','Aerotrans',43),
	 (NULL,'AED','Aerotrans Airlines',43),
	 ('AEROVIZ','VIZ','Aerovis Airlines',48),
	 ('sovet','WER','AeroWorld ',43),
	 ('FLYINGOLIVE','DNC','Aeroynamics Malaga',13),
	 ('TWEETY','KIE','Afit',10),
	 ('AGROAR','GRR','Agroar - Trabalhos Aereos',40);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AGROLET','AGZ','Agrolet-Mci',46),
	 ('AIGLE AZUR','AAF','Aigle Azur',16),
	 ('ADRIATIC','AHR','Air Adriatic',21),
	 ('ALIZE','RLZ','Air Alize',16),
	 ('AIR ALPHA','AHA','Air Alpha Greenland',11),
	 ('ALPAV','LPV','Air Alps Aviation',3),
	 ('MERMAID','MMD','Air Alsie',11),
	 ('ANASTASIA','RUD','Air Anastasia',48),
	 (NULL,'ASN','Air and Sea Transport',43),
	 ('ARCHIPELS','RHL','Air Archipels',16);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SNOWBIRD','EUK','Air Atlanta Europe',17),
	 ('ATLANTA','ABD','Air Atlanta Icelandic',25),
	 ('ATLANTIC','AAG','Air Atlantique',17),
	 ('REUNION','REU','Air Austral',16),
	 ('AIRBALTIC','BTI','Air Baltic',31),
	 ('DOC AIR','LZP','Air Ban',6),
	 ('AGYDAL','BBT','Air Bashkortostan',43),
	 ('AIR BERLIN','BER','Air Berlin',10),
	 ('AIR BOSNA','BON','Air Bosna',4),
	 (NULL,'BUR','Air Bucharest',41);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AIRCAL','TPC','Air Cal',16),
	 ('AIRCALIN','ACI','Air Caledonie International',16),
	 ('FRENCH WEST','FWI','Air Cara�bes',16),
	 ('CAR LINE','CAJ','Air Caraibes Atlantique',16),
	 (NULL,'ACV','Air Charter Service',17),
	 ('RACER','RCC','Air Charters Eelde',37),
	 ('AIRCITY','ECE','Air City',10),
	 ('AIR COLUMBUS','CBS','Air Columbus',48),
	 ('CONCORDE AIR','KGD','Air Concorde',6),
	 ('AIR CONSUL','CNU','Air Consul',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('CONTRACT','ABR','Air Contractors',23),
	 ('AIRCORPORATE','CPV','Air Corporate',26),
	 ('Cudlua','CUD','Air Cudlua',17),
	 (NULL,'AFS','Air Data',17),
	 ('DOLOMOTI','DLA','Air Dolomiti',26),
	 ('Engiadina','RQX','Air Engiadina-BRN',8),
	 ('AESTE','EET','Air Este',13),
	 ('EUROPA','AEA','Air Europa',13),
	 ('AIR EUROPE','AEL','Air Europe',26),
	 ('AIR-EVANS','VAE','Air Evans',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SUNBEAM','EVE','Air Evex',10),
	 ('COMPANY EXEC','IVE','Air Executive',13),
	 (NULL,'XEC','Air Executive Charter',10),
	 ('EXEL COMMUTER','AXL','Air Exel',37),
	 (NULL,'AXE','Air Explore',46),
	 ('LUNA','AEQ','Air Express',44),
	 ('AIR FINLAND','FIF','Air Finland',14),
	 ('FOYLE','UPA','Air Foyle',17),
	 ('AIRFRANS','AFR','Air France',16),
	 ('AIR GLACIERS','AGV','Air Glaciers',8);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('GREENLAND','GRL','Air Greenland',11),
	 ('Air Hamburg','AHO','Air Hamburg (AHO)',10),
	 ('FAXI','FXI','Air Iceland',25),
	 ('INTERSALONIKA','NSK','Air Intersalonika',20),
	 ('AIR ITALY','AEY','Air Italy',26),
	 ('MUSKETEER','MQT','Air ITM',16),
	 ('AIRJETSUL','AJU','Air Jetsul',40),
	 ('AIR KIROVOGRAD','KAD','Air Kirovograd',48),
	 ('AIR KLAIPEDA','KLD','Air Klaipeda',29),
	 ('LAZUR BEE-GEE','LZR','Air Lazur',6);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('HELLAS LIFT','IFI','Air Lift',20),
	 ('KAUNAS','KLA','Air Lithuania',29),
	 ('LITUANICA','LTU','Air Lituanica',29),
	 ('LIVONIA','LIV','Air Livonia',12),
	 ('AIRLUXOR','LXR','Air Luxor',40),
	 ('ICO-AIR','KAM','Air Mach',26),
	 ('ALADA AIR','DRD','Air Madrid',13),
	 ('AIR MALTA','AMC','Air Malta',36),
	 ('FLIGHT TAXI','EFC','Air Mana',16),
	 ('AEROMAX','RMX','Air Max',6);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AIR MED','MCD','Air Medical',17),
	 ('MEDITERRANEE','BIE','Air Mediterranee',16),
	 ('WESTMID','MCB','Air Mercia',17),
	 ('AIR MOLDOVA','MLD','Air Moldova',33),
	 ('MONTY','MTY','Air Montegomery',17),
	 ('MONTENEGRO','AMN','Air Montenegro',34),
	 ('AIR MOOREA','TAH','Air Moorea',16),
	 ('AIR NAV','ANB','Air Navigation And Trading Co. Ltd.',17),
	 ('AIR NOSTRUM','ANE','Air Nostrum',13),
	 ('HERON','ADH','Air One',26);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('CITYLINER','CYL','Air One Cityliner',26),
	 (NULL,'AOE','Air One Executive',26),
	 ('AIRPACK EXPRESS','PCK','Air Pack Express',13),
	 ('AIRPAL','PLL','Air Pal',13),
	 ('AIR PARTNER','ACG','Air Partner',17),
	 ('RED COMET','MPD','Air Plus Comet',13),
	 ('PULLMANTUR','PLM','Air Pullmantur',13),
	 (NULL,'SPM','Air Saint Pierre',16),
	 ('SCORPIO UNIVERS','SCU','Air Scorpio',6),
	 ('GREECE AIRWAYS','GRE','Air Scotland',20);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AIR SERBIA','ASL','Air Serbia',42),
	 ('SERVICE CENTER','RCX','Air Service Center',26),
	 ('DEGGER','DEG','Air Service Groningen',37),
	 ('SLOVAKIA','SVK','Air Slovakia',46),
	 ('AIR SOFIA','SFB','Air Sofia',6),
	 ('PIRATE','PIE','Air South West',17),
	 ('SWALLOW','WOW','Air Southwest',17),
	 ('AIRSPEC','ASX','Air Special',9),
	 ('AIR SPORT','MSK','Air Sport',6),
	 ('Air Srpska','SBK','Air Srpska',4);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SURESTE','AIS','Air Sureste',13),
	 ('TAHITI AIRLINES','THT','Air Tahiti Nui',16),
	 ('TAXI BIRD','HAT','Air Taxi',16),
	 ('TOMISKO CARGO','TOH','Air Tomisko',42),
	 ('AIR TRACTOR','AOU','Air Tractor',21),
	 ('SNOOPY','ATJ','Air Traffic GmbH',10),
	 ('TRANS EUROPE','EAT','Air Transport',46),
	 ('MULTI','ATQ','Air Transport Schiphol',37),
	 ('TURQUOISE','RTQ','Air Turquoise',16),
	 ('AIR UKRAINE','UKR','Air Ukraine',48);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AIR UMBRIA','UMB','Air Umbria',26),
	 ('URGA','URG','Air Urga',48),
	 ('AIR VALENCIA','AVZ','Air Valencia',13),
	 (NULL,'VIM','Air VIA',6),
	 ('AIRSAR','AHS','Air Viggi San Raffaele',26),
	 ('AEROVIP','RVP','Air VIP',40),
	 ('RED DRAGON','AWW','Air Wales',17),
	 ('AIRWALSER','WLR','Air Walser',26),
	 ('ARBAS','BSB','Air Wings',33),
	 ('YUGAIR','YRG','Air Yugoslavia',42);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AIR ZERMATT','AZF','Air Zermatt AG',8),
	 ('HAWKHUNGARY','HKH','Air-Invest',22),
	 ('EOLE','EOL','Airailes',16),
	 ('AIRGOAT','RGT','Airbourne School of Flying',17),
	 ('AIRBRIDGE CARGO','ABW','AirBridge Cargo',43),
	 ('AIRBUS FRANCE','RBU','Airbus France',16),
	 ('AIRBUS INDUSTRIE','AIB','Airbus Industrie',16),
	 ('BELOUGA','BGA','Airbus Transport International',16),
	 ('BARCOL','BKL','Aircompany Barcol',43),
	 ('AIR CHAIKA','CHJ','Aircompany Chaika',48);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('GRODNO','GRX','Aircompany Grodno',7),
	 ('ROSAVIA','URA','Aircompany Rosavia',48),
	 ('AIR YAKUTIA','SYL','Aircompany Yakutia',43),
	 ('AIRDEAL','ADU','Airdeal Oy',14),
	 (NULL,'AIT','Airest',12),
	 ('AIRFIX','FIX','Airfix Aviation',14),
	 (NULL,'AFX','Airfreight Express',17),
	 ('AIRLEC','ARL','Airlec - Air Aquitaine Transport',16),
	 ('AIRLINAIR','RLA','Airlinair',16),
	 ('ALANIA','OST','Airline Alania',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SKOL','CDV','Airline Skol',43),
	 ('REMONT AIR','VAZ','Airlines 400',43),
	 ('AIRLINK','JAR','Airlink',3),
	 ('HIGHFLYER','HYR','Airlink Airways',23),
	 ('AIRLIN','LKS','Airlink Solutions',13),
	 (NULL,'AO1','AirOne Atlantic',46),
	 ('AIRHOLD','AHH','Airplanes Holdings',23),
	 ('AEROBRA','BRP','Airport Bratsk',43),
	 ('IPULL','IPL','Airpull Aviation',13),
	 ('russiancloud','RRJ','AirRussia',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AIRSHARE','SHH','Airshare Holdings',17),
	 ('MOROZOV','ASE','Airstars',43),
	 ('AIRTIME','IME','Airtime Charters',17),
	 (NULL,'VAB','Airtrans Ltd',43),
	 ('AIR VALLEE','RVL','Airvallee',26),
	 ('AIRVENTURE','RVE','Airventure',5),
	 ('GARONNE','WAY','Airways',16),
	 ('DARTMOOR','DRM','Airways Flight Training',17),
	 ('NORWING','NWG','Airwing',38),
	 ('AIRWINGS','WGS','Airwings oy',14);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('MANN','AMH','Alan Mann Helicopters Ltd.',17),
	 ('ALBA','AFQ','Alba Servizi Aerotrasporti',26),
	 ('ALBANIAN','LBC','Albanian Airlines',2),
	 (NULL,'LAV','AlbaStar',13),
	 ('ALBANWAYS','LBW','Albatros Airways',2),
	 ('ALBION','ALD','Albion Aviation',17),
	 ('ALEXANDROS','AXN','Alexandair',20),
	 ('BLUE ALFA','AFA','Alfa Air',9),
	 ('ALIA','AIU','Alicante Internacional Airlines',13),
	 ('ALIDA','LID','Alidaunia',26);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('ALIPARMA','PAJ','Aliparma',26),
	 ('ALITALIA','AZA','Alitalia',26),
	 ('ALIEXPRESS','SMX','Alitalia Express',26),
	 ('ALIVEN','LVN','Aliven',26),
	 ('ALL CHARTER','BLA','All Charter Limited',17),
	 (NULL,'N99','All Europe',17),
	 (NULL,'N77','All Spain',13),
	 ('ACEFORCE','ALF','Allied Command Europe (Mobile Force)',5),
	 ('STEF','LUC','Alninati Aeronautics',8),
	 ('ALPI EAGLES','ELG','Alpi Eagles',26);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('ALPINER','ALP','Alpliner AG',8),
	 ('MIRNY','DRU','Alrosa Mirny Air Enterprise',43),
	 ('ALROSA','LRO','Alrosa-Avia',43),
	 ('ALSAIR','LSR','Alsair',16),
	 ('ALTAGNA','AGH','Altagna',16),
	 ('AMADEUS','AGT','Amadeus Global Travel Distribution',13),
	 ('AMAPOLA','APF','Amapola Flyg AB',44),
	 ('GINTA','GNT','Amber Air',29),
	 ('AMER AIR','AMK','Amerer Air',3),
	 ('EXPERT','XPE','Amira Air',3);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'XMG','AMS Group',43),
	 ('AMSTEL','AAN','Amsterdam Airlines',37),
	 ('Andalus','ANU','Andalus Lineas Aereas',13),
	 ('SARMA','AGU','Angara Airlines',43),
	 ('ANGLO','ANC','Anglo Cargo',17),
	 ('ANTANIK','NAU','Antanik-Air',48),
	 ('ANTONOV BUREAU','ADB','Antonov Airlines',48),
	 ('French Lines','AOM','AOM French Airlines',16),
	 ('APATAS','LYT','Apatas Air',29),
	 ('ARAVCO','ARV','Aravco Ltd.',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('ARCHER','DHM','Archer Aviation',17),
	 ('Arctic Norway','AKR','Arctic Air',38),
	 ('ARCUS AIR','AZE','Arcus-Air Logistic',10),
	 ('ARIABIRD','ARW','Aria',16),
	 ('ARKEFLY','TFL','Arkefly',37),
	 ('DVINA','OAO','Arkhangelsk 2 Aviation Division',43),
	 ('ARMYAIR','AAC','Army Air Corps',17),
	 ('AIR-ARP','URP','ARP 410 Airlines',48),
	 ('ARTEM-AVIA','ABA','Artem-Avia',48),
	 ('ARTHELICO','RTH','Artis',16);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'XKX','ASECNA',16),
	 (NULL,'XXX','ASL',5),
	 (NULL,'XJA','Assistance Aeroportuaire de L''Aeroport de Paris',16),
	 ('FLYSTAR','AEU','Astraeus',17),
	 ('AIR ASTRAKHAN','ASZ','Astrakhan Airlines',43),
	 ('ATLANT HUNGARY','ATU','Atlant Aerobatics Ltd.',22),
	 ('ATLANT-SOYUZ','AYZ','Atlant-Soyuz Airlines',43),
	 ('HIGHER','HGH','Atlantic Air Lift',16),
	 ('NEPTUNE','NPT','Atlantic Airlines',17),
	 ('FAROELINE','FLI','Atlantic Airways',15);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('FAROECOPTER','FAC','Atlantic Helicopters',11),
	 ('AIR COURIER','RCU','Atlantic S.L.',13),
	 ('TRIPLE-A','TLB','Atlantique Air Assistance',16),
	 ('TRIDENT','TDT','Atlas Helicopters',17),
	 ('Atlas Ukraine','UJX','AtlasGlobal Ukraine',48),
	 ('TECHSERVICE','CPF','ATS Private Company',48),
	 ('AUDELI','ADI','Audeli Air',13),
	 ('AUGSBURG-AIR','AUB','Augsburg Airways',10),
	 ('AUGUSTA','AUF','Augusta Air Luftfahrtunternehmen',10),
	 ('STORK','ISM','Auo Airclub AIST-M',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AUOS','AUK','AUOS',17),
	 ('AURELA','LSK','Aurela',29),
	 ('AYLINE','AUR','Aurigny Air Services',17),
	 ('AIR AURORA','URR','Aurora Airlines',45),
	 ('AUSTRIAN','AUA','Austrian Airlines',3),
	 (NULL,'AAT','Austrian Airtransport',3),
	 ('KENT HELI','AVH','AV8 Helicopters',17),
	 ('AVAG AIR','MBA','Avag Air',3),
	 ('AIR AVALAIR','VAI','Avalair',42),
	 ('AVANTI AIR','ATV','Avanti Air',10);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AIR VICTOR','VBC','AVB-2004 Ltd',6),
	 (NULL,'ACC','Avcard Services',17),
	 ('AERO AVCOM','AOC','AVCOM',43),
	 ('AVCORP','AVP','Avcorp Registrations',17),
	 (NULL,'AUP','Avia Business Group',43),
	 ('AVIACONSULT','AJF','Avia Consult Flugbetriebs',3),
	 ('AVIASUD','AVU','Avia Sud A',16),
	 (NULL,'ABI','Aviabus',43),
	 ('ZITOTRANS','AZS','Aviacon Zitotrans Air Company',43),
	 ('Avex','AEH','Aviaexpress',22);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('EXPRESSAVIA','VXX','Aviaexpress Aircompany',48),
	 (NULL,'IWS','Aviainvest',43),
	 ('NEW AVIAL','NVI','Avial NV Aviation Company',43),
	 ('AVIALESOOKHRANA','FFA','Avialesookhrana',43),
	 ('VLADLIFT','VLV','Avialift Vladivostok',43),
	 ('AVIALSA','AVS','Avialsa T-35',13),
	 ('HANDLING','GHL','Aviance',17),
	 ('AVIANERGO','ERG','Avianergo',43),
	 (NULL,'OSO','Aviapartner Limited Company',43),
	 ('PASLAUGA','AVX','Aviapaslauga',29);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AVIAPRAD','VID','Aviaprad',43),
	 ('AVIAPROM','XAV','Aviaprom Enterprises',43),
	 ('IALSI','VVA','Aviast Air',43),
	 ('TUPOLEVAIR','TUP','Aviastar-Tu',43),
	 ('BEAUPAIR','AVB','Aviation Beaufort',17),
	 ('AVIAMERIDIAN','MMM','Aviation Company Meridian',43),
	 ('TIRPA','DEF','Aviation Defense Service',16),
	 ('FRENCH ARMY','FMY','Aviation Legere De L''Armee De Terre',16),
	 ('AVIATOR','AVW','Aviator Airways',20),
	 ('AVIAVILSA','LVR','Aviavilsa',29);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AXAVIA','AXV','Aviaxess',16),
	 ('IAZUR','VZR','Aviazur',16),
	 ('AVIES','AIA','Avies',12),
	 (NULL,'HQO','Avinor',38),
	 (NULL,'FNM','Avio Nord',26),
	 ('AVIO SLUZBA','SLU','Avio Sluzba',42),
	 ('BULGARIAN','BGF','Aviodetachment-28',6),
	 ('GENEX','AGX','Aviogenex',42),
	 ('AVIOSTART','VSR','Aviostart AS',6),
	 (NULL,'ESO','Avitat',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AXIS','AXY','Axis Airways',16),
	 ('AZOV AVIA','AZV','Azov Avia Airlines',48),
	 ('AZZURRA','AZI','Azzurra Air',26),
	 ('Air Bosna','BON','B&H Airlines',4),
	 ('FLYER','CFE','BA CityFlyer',17),
	 ('RAPEX','RPX','BAC Express Airlines',17),
	 (NULL,'BAC','BAC Leasing Limited',17),
	 ('BACH','BCF','BACH Flugbetriebsges',3),
	 ('FELIX','BAE','BAE Systems',17),
	 ('AVRO','WFD','BAE Systems',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('TARNISH','WTN','BAE Systems',17),
	 ('BASHKIRIAN','BTC','BAL Bashkirian Airlines',43),
	 ('BALEAR EXPRESS','BEF','Balear Express',13),
	 ('BALKAN AGRO','BAA','Balkan Agro Aviation',6),
	 ('Baltic','BA1','Baltic Air lines',31),
	 ('BALTIC AIRLINES','BLL','Baltic Airlines',43),
	 ('BALTIC JET','BJC','Baltic Jet Aircompany',31),
	 ('BALTIJAS HELICOPTERS','BTH','Baltijas Helicopters',31),
	 ('BALTYKA','BTK','Baltyka',48),
	 ('BANAIR','BBA','Bannert Air',3);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('NORDFLIGHT','NKF','Barents AirLink',44),
	 ('SEELINE','CLN','Barnes Olsen Aeroleasing',17),
	 ('COASTRIDER','BRO','BASE Regional Airlines',37),
	 ('BBN','EGH','BBN-Airways',17),
	 ('BOBCAT','BCT','BCT Aviation',17),
	 ('BEARFLIGHT','BFG','Bear Flight',44),
	 ('PROVOST','PVO','Bearing Supplies Limited',17),
	 ('BLUECOPTER','BEH','Bel Air Helicopters',11),
	 (NULL,'FOS','Bel Limited',43),
	 ('BELAIR','BHP','Belair Airlines',8);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('BELARUS AVIA','BRU','Belavia Belarusian Airlines',7),
	 ('BELGAVIA','BLG','Belgavia',5),
	 ('BELGIAN AIRFORCE','BAF','Belgian Air Force',5),
	 ('BELGIAN ARMY','AYB','Belgian Army',5),
	 ('BELGIAN NAVY','NYB','Belgian Navy',5),
	 ('BELOGORYE','BED','Belgorod Aviation Enterprise',43),
	 ('ALBAN-BELLE','LBY','Belle Air',2),
	 ('BELLESAVIA','BLC','Bellesavia',7),
	 ('SCOOP','HAX','Benair',38),
	 ('PALEMA','PEB','Benders Air',44);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('BERGEN AIR','BGT','Bergen Air Transport',38),
	 (NULL,'BAX','Best Aero Handling Ltd',43),
	 ('BAKERFLIGHT','BKF','BF-Lento OY',14),
	 ('BALKAN HOLIDAYS','BGH','BH Air',6),
	 ('BILAIR','BIL','Billund Air Center',11),
	 ('BINAIR','BID','Binair',10),
	 (NULL,'BGY','Bingo Airways',39),
	 (NULL,'IBB','Binter Canarias',13),
	 ('BERLIN BEAR','BZA','Bizair Fluggesellschaft',10),
	 ('BIZZ','BIZ','Bizjet Ltd',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('COSMOS','CKM','BKS Air (Rivaflecha)',13),
	 ('SWEEPER','LED','Blom Geomatics',38),
	 ('BLUE TRANSPORT','JOR','Blue Air',41),
	 ('BLUE SPEED','VOL','Blue Chip Jet',44),
	 ('BLUE ISLAND','BCI','Blue Islands',17),
	 ('BLUEWAY','BLJ','Blue Jet',13),
	 ('BLUE BERRY','BLE','Blue Line',16),
	 ('BLUE PANOROMA','BPA','Blue Panorama Airlines',26),
	 ('SKY BLUE','BSW','Blue Sky Airways',9),
	 ('BLUE SWANN','BSJ','Blue Swann Aviation',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('BLUE WINGS','BWG','Blue Wings',10),
	 ('BLUEFIN','BLF','Blue1',14),
	 (NULL,'BBG','Bluebird Airways (BZ)',20),
	 ('BLUE CARGO','BBD','Bluebird Cargo',25),
	 ('MIDLAND','BMA','bmi',17),
	 ('BABY','BMI','bmibaby',17),
	 ('BMW-FLIGHT','BMW','BMW',10),
	 ('VECTIS','BNG','BN Group Limited',17),
	 ('RED HEAD','RHD','Bond Air Services',17),
	 ('BOND AVIATION','EBA','Bond Aviation',26);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('BOND','BND','Bond Offshore Helicopters',17),
	 ('BONUS','BPT','Bonus Aviation',17),
	 ('BOOKAJET','BOO','Bookajet Limited',17),
	 ('BLACKBOX','RRS','Boscombe Down DERA (Formation)',17),
	 ('Braathens','BRA','Braathens',38),
	 ('BRAVO EUROPE','BBV','Bravo Airlines',13),
	 ('AVIABREEZE','BRE','Breeze Ltd',48),
	 ('BRIANSK-AVIA','BRK','Briansk State Air Enterprise',43),
	 ('BRIGGS','BME','Briggs Marine Environmental Services',17),
	 ('BRIGHTAIR','BHT','Bright Air',37);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('BRIGHT SERVICES','BRW','Bright Aviation Services',6),
	 ('CLIFTON','CLF','Bristol Flying Centre',17),
	 ('BRISTOW','BHL','Bristow Helicopters',17),
	 ('BRITAIR','BZH','Brit Air',16),
	 ('BRITANNIA','BAL','Britannia Airways',17),
	 ('SPEEDBIRD','BAW','British Airways',17),
	 ('SANTA','XMS','British Airways',17),
	 ('SHUTTLE','SHT','British Airways Shuttle',17),
	 ('PENGUIN','BAN','British Antarctic Survey',17),
	 (NULL,'BCL','British Caribbean Airways',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('BACKER','BCR','British Charter',17),
	 ('BRINTEL','BIH','British International Helicopters',17),
	 ('BRITISH MEDICAL','BMD','British Medical Charter',17),
	 ('BEE MED','LAJ','British Mediterranean Airways',17),
	 (NULL,'BMR','British Midland Regional',17),
	 ('BRITISH NORTH','BNW','British North West Airlines',17),
	 ('BRITISH','BRT','British Regional Airlines',17),
	 ('SKYNEWS','SKH','British Sky Broadcasting',17),
	 ('BEE-LINE','DAT','Brussels Airlines',5),
	 ('XENIA','BXI','Brussels International Airlines',5);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('BEETEE-SLAVUTA','BTT','BT-Slavuta',48),
	 ('BASE','BPS','Budapest Aircraft Services/Manx2',22),
	 (NULL,'BG1','BudgetAir',10),
	 ('BUGAVIA','BGM','Bugulma Air Enterprise',43),
	 ('BUKOVYNA','BKV','Bukovyna',48),
	 ('FLYING BULGARIA','LZB','Bulgaria Air',6),
	 ('BULGARIAN WINGS','BVC','Bulgarian Aeronautical Centre',6),
	 ('BULGARIAN CHARTER','BUC','Bulgarian Air Charter',6),
	 ('PIROL','BPO','Bundepolizei-Fliegertruppe',10),
	 (NULL,'XDA','Bureau Veritas',16);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('BURAL','BUN','Buryat Airlines Aircompany',43),
	 ('BUSINESS AVIATION','BCV','Business Aviation Center',48),
	 ('AUSTROJET','AUJ','Business Flight Salzburg',3),
	 ('BUSINESS FLIGHT','BFS','Business Flight Sweden',44),
	 ('SCANJET','SCJ','Business Jet Sweden',44),
	 ('BUZZARD','BZZ','Butane Buzzard Aviation Corporation',17),
	 ('BUZZ','BUZ','Buzz Stansted',17),
	 ('UKAY','UKA','Buzzaway Limited',17),
	 ('BRITWORLD','BWL','BWA (2002) Ltd',17),
	 ('BYLINA','BYL','Bylina Joint-Stock Company',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('CAPRI','ORO','C N Air',13),
	 ('CABAIR','CBR','Cabair College of Air Training',17),
	 ('CABI','CBI','CABI',48),
	 ('AMBASSADOR','CWD','Caernarfon Airworld',17),
	 ('AIRCAI','CPI','CAI',26),
	 ('CALIMA','CLI','Calima Aviacion',13),
	 ('CAMEO','CMR','CAM Air Management',17),
	 ('HELIASTURIAS','HSO','Campania Helicopteros De Transporte',13),
	 (NULL,'CNF','Canaryfly',13),
	 ('PRESTIGE','EGL','Capital Trading Aviation',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('CAMBRIAN','CWN','Cardiff Wales Flying Club',17),
	 ('WHITE PELICAN','CRG','Cargoitalia',26),
	 ('CARGOLUX','CLX','Cargolux',30),
	 ('CARIBBEAN','CLT','Caribbean Air Transport',37),
	 ('CARILL','CVG','Carill Aviation',17),
	 ('CARPATAIR','KRP','Carpatair',41),
	 ('Smartwings','SMW','Carpatair Flight Training',41),
	 ('EUROCAT','CAZ','Cat Aviation',8),
	 ('CATEX','TEX','Catex',16),
	 (NULL,'CIF','CB Airways UK ( Interliging Flights )',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('TOMCAT','CCF','CCF Manager Airline',10),
	 ('CECIL','CIL','Cecil Aviation',17),
	 ('CEGA','CEG','Cega Aviation',17),
	 ('CELLOJET','CLJ','Cello Aviation',17),
	 ('CELTAIR','CEC','Celtic Airways',17),
	 ('CELTIC','CWE','Celtic West',17),
	 (NULL,'CNA','Centavia',42),
	 ('CENTEV','CEV','Cente D''Essais En Vol',16),
	 ('CENTERVOL','CVO','Center Vol',13),
	 ('CENTER-SOUTH','CTS','Center-South',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'CCG','Central Connect Airlines',9),
	 ('EUROCENTRAL','CMA','Central European Airlines',9),
	 ('CENTRALWINGS','CLW','Centralwings',39),
	 ('GEO CENTRE','CGS','Centre of Applied Geodynamica',43),
	 ('AVIACENTRE','CVC','Centre-Avia',43),
	 ('FORCAN','ACF','Centro de Formacion Aeronautica de Canarias',13),
	 ('CHALLAIR','CLG','Chalair Aviation',16),
	 ('AIRISTO','CLS','Challenge Air Transport',10),
	 ('CHAMPAGNE','CPH','Champagne Airlines',16),
	 ('CHARTER WIEN','CHW','Charter Air',3);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'SCH','CHC Airways',37),
	 ('HELIBIRD','HBI','CHC Denmark',11),
	 ('HELIBUS','HKS','CHC Helikopter Service',38),
	 ('cheapflying','FQR','CheapFlyingInternational',16),
	 ('CHEBAIR','CBB','Cheboksary Airenterprise JSC',43),
	 ('CHERL','CHZ','Cherline',43),
	 ('CHERAVIA','CMK','Chernomor-Avia',43),
	 ('CHITA','CHF','Chitaavia',43),
	 ('CHRISTOPHORUS','OEC','Christophorus Flugrettungsverein',3),
	 ('CHURCH FENTON','CFN','Church Fenton Flying Training Unit',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('CIMBER','CIM','Cimber Air',11),
	 ('CIRRUS AIR','RUS','Cirrus Airlines',10),
	 ('SWEDESTAR','SDR','City Airline',44),
	 (NULL,'CIP','City-Air Germany',10),
	 ('AIR CHESTER','CAQ','Cityair (Chester) Limited',17),
	 ('CITYFLY','CII','Cityfly',26),
	 ('CITY-IRELAND','BCY','CityJet',23),
	 ('CITYHUN','CNB','Cityline Hungary',22),
	 ('CALIMERA','CIA','Civil Aviation Authority',46),
	 ('CALIBRA','CBA','Civil Aviation Inspectorate of the Czech Republic',9);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('CLAESSENS','FMC','Claessens International Limited',17),
	 ('CALEDONIAN','CSF','Clasair',17),
	 ('CLOWES','CLD','Clowes Estates Limited',17),
	 ('SPACEJET','SDJ','Club 328',17),
	 ('CLUBAIR','ISG','Club Air',26),
	 ('KNET','CNT','CNET',16),
	 ('COAST CENTER','CST','Coast Air',38),
	 ('COLT','COH','Coltishall Flying Training Unit',17),
	 ('COMEX','CDE','Comed Group',17),
	 ('FLYNN','FYN','Comfort Air',10);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('COMLUX','CLA','Comlux Aviation',8),
	 ('COMMODORE','CMH','Commair Aviation',17),
	 ('COTAM','CTM','Commandement Du Transport Aerien Militaire Francais',16),
	 ('COMPRIP','CGR','Compagnia Generale Ripreseaeree',26),
	 (NULL,'AIF','Compania Aerea de Valencia',13),
	 ('AEROTECNICAS','ATF','Compania Aerotecnicas Fotograficas',13),
	 ('STELLAIR','LCT','Compania De Actividades Y Servicios De Aviacion',13),
	 ('TAVISA','TAV','Compania de Servicios Aereos Tavisa',13),
	 ('HELISURESTE','HSE','Compania Helicopteros Del Sureste',13),
	 ('TAS HELICOPTEROS','HSS','Compania Transportes Aereos Del Sur',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('COMPANY FLIGHT','CYF','Company Flight',11),
	 ('COMPASS','CPS','Compass International Airways',17),
	 (NULL,'COE','Comtel Air',3),
	 ('CONCORDAVIA','COD','Concordavia',48),
	 ('CONDOR BERLIN','CIB','Condor',10),
	 ('CONDOR','CFG','Condor Flugdienst',10),
	 ('TYPHOON','CBY','Coningsby Flying Training Unit',17),
	 ('CONSTANTA','UZA','Constanta Airline',48),
	 ('CONTACTAIR','KIS','Contact Air',10),
	 ('CONTAIR','PVV','Continental Airways',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SURVEYOR','SVY','Cooper Aerial Surveys',17),
	 ('AIRCAT','CAT','Copenhagen Airtaxi',11),
	 ('Copex','CX-','Copenhagen Express',11),
	 ('COPTERLINE','AAQ','Copterline',14),
	 ('CORSAIR','CRL','Corsairfly',16),
	 ('CORSICA','CCM','Corse-Mediterranee',16),
	 ('COTTESMORE','COT','Cottesmore Flying Training Unit',17),
	 ('MOCKINGBIRD','MGB','Coulson Flying Service',17),
	 ('COWI','COW','Cowi',37),
	 ('COYNE AIR','COY','Coyne Aviation',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AERONAUT','CFD','Cranfield University',17),
	 ('CRANWELL','CWL','Cranwell Flying Training Unit',17),
	 ('CREST','CAN','Crest Aviation',17),
	 ('TRANS UNIVERSAL','KRM','Crimea Universal Avia',48),
	 ('CROATIA','CTN','Croatia Airlines',21),
	 ('CROATIAN AIRFORCE','HRZ','Croatian Air Force',21),
	 ('CROSSAIR','CRX','Cross Aviation',17),
	 ('Cigogne','ECC','Crossair Europe',8),
	 ('OXFORD','CSE','CSE Aviation',17),
	 ('CYGNUS AIR','RGN','Cygnus Air',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('CZECH AIR FORCE','CEF','Czech Air Force',9),
	 ('AIRHANDLING','AHD','Czech Air Handling',9),
	 ('CSA-LINES','CSA','Czech Airlines',9),
	 ('CZECHIA','CIE','Czech Government Flying Service',9),
	 ('DAGAL','DAG','Dagestan Airlines',43),
	 ('TWIN STAR','DCS','Daimler Chrysler Aviation',10),
	 ('DALAVIA','KHB','Dalavia',43),
	 (NULL,'DAN','Dan-Air London',17),
	 ('DANCOPTER','DOP','Dancopter',11),
	 ('DANISH AIRFORCE','DAF','Danish Air Force',11);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('DANISH ARMY','DAR','Danish Army',11),
	 ('DANISH NAVY','DNY','Danish Navy',11),
	 ('DANU','DNU','Danu Oro Transportas',29),
	 ('DARTA','DRT','Darta',16),
	 ('DARWIN','DWT','Darwin Airline',8),
	 ('PILGRIM','GOB','Dash Aviation',17),
	 ('DASNA','DGX','Dasnair',8),
	 (NULL,'DAB','Dassault Aviation',16),
	 ('DASSAULT','DSO','Dassault Falcon Service',16),
	 ('DANISH','DTR','DAT Danish Air Transport',11);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('DATENT','ENT','DAT Enterprise Limited',17),
	 ('DAUAIR','DAU','Dauair',10),
	 (NULL,'DCO','David Crawshaw Consultants Limited',17),
	 ('SPEEDWAY','BAG','dba',10),
	 ('IASON','IAY','Deadalos Flugtbetriebs',3),
	 ('JET SERVICE','DEA','Delta Aerotaxi',26),
	 ('KEMBLEJET','KMB','Delta Engineering Aviation',17),
	 ('DELTA EXPRESS','DLI','Delta Express International',48),
	 ('DENIM','DNM','Denim Air',37),
	 ('FORESTALES','FGC','Departmento De Agricultura De La Generalitat De Cataluna',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('GAUNTLET','BDN','DERA Boscombe Down',17),
	 ('DESNA','DSN','DESNA',48),
	 (NULL,'DLT','Deutsche Luftverkehrsgesellschaft',10),
	 (NULL,'DWD','Deutsche Luftverkehrsgesellschaft (DLT)',10),
	 ('CIVIL AIR AMBULANCE','AMB','Deutsche Rettungsflugwacht',10),
	 ('LUFO','LFO','Deutsches Zentrum fur Luft-und Raumfahrt EV',10),
	 ('Dexter','DXT','Dexter (DXT)',43),
	 ('VOLANTE','VLF','DFS UK Limited',17),
	 ('WORLD EXPRESS','DHK','DHL Air',17),
	 ('DI AIR','DIS','Di Air',42);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('DIPFREIGHT','DIP','Diplomatic Freight Services',17),
	 ('ENA','ENA','Direccion General de Aviacion Civil y Telecomunicasciones',13),
	 (NULL,'DSV','Direct Aero Services',41),
	 (NULL,'DCT','Direct Flight',17),
	 ('DIX FLIGHT','DIX','Dix Aviation',10),
	 ('GERMAN POLAR','GPL','DLR',10),
	 ('DNIEPRO','UDN','Dniproavia',48),
	 ('DOBROLET','DOB','Dobrolet',43),
	 ('MAYORAL','MYO','Dominguez Toledo (Grupo Mayoral)',13),
	 ('DOMODEDOVO','DMO','Domodedovo Airlines',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('DONAIR','DON','Donair Flying Club',17),
	 ('DONBASS AERO','UDC','DonbassAero',48),
	 ('DORNIER','DOR','Dornier',10),
	 ('DREAM CATCHER','DCA','Dreamcatcher Airways',17),
	 ('SEAGULL','DBK','Dubrovnik Air',21),
	 ('LION KING','DUK','Ducair',30),
	 ('DUCHESS','DBJ','Duchess of Britany (Jersey) Limited',17),
	 ('FLY DUO','DUO','Duo Airways',17),
	 ('DUTCHBIRD','DBR','Dutchbird',37),
	 ('DYNAMIC','DYE','Dynamic Air',37);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AERO-ESCOLA','EAD','EAA Escola De Aviacao Aerocondor',40),
	 ('ARCTIC EAGLE','FEI','Eagle Air Iceland',25),
	 ('GYPSY','GYP','Eagle Aviation',17),
	 ('FRENCH EAGLE','EGN','Eagle Aviation France',16),
	 ('EAGLES','EGS','Eagles Airlines',26),
	 ('COSTOCK','CTK','East Midlands Helicopters',17),
	 ('EASTEX','EAX','Eastern Air Executive',17),
	 ('EASTFLIGHT','EZE','Eastern Airways',17),
	 ('GENESIS','GNS','Eastern Executive Air Charter',17),
	 ('EASY','EZY','easyJet',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('EDELWEISS','EDW','Edelweiss Air',8),
	 ('SALTIRE','EDC','Edinburgh Air Charter',17),
	 ('EVER FLIGHT','EFD','EFD Eisele Flugdienst',10),
	 ('FLUGSERVICE','FSD','EFS-Flugservice',10),
	 ('AIR EXPORTS','EIX','Ei Air Exports',23),
	 ('EIRJET','EIR','Eirjet',23),
	 ('COOL','EIS','EIS Aircraft',10),
	 ('MOTION','LBR','Elbe Air Transport',10),
	 ('ELAVIA','NLK','Elbrus-Avia Air Enterprise',43),
	 ('ELICAR','PDV','Elicar',26);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('ELIDOLOMITI','EDO','Elidolomiti',26),
	 ('ELILOBARDIA','ELB','Elieuro',26),
	 ('ELIFRIULIA','EFG','Elifriulia',26),
	 ('LARIO','ELH','Elilario Italia',26),
	 ('LOMBARDA','EOA','Elilombarda',26),
	 ('ELIMEDITERRANEA','MEE','Elimediterranea',26),
	 ('ELIOS','VUL','Elios',26),
	 ('ELIOSSOLA','EOS','Eliossola',26),
	 ('ELIPIU','IEP','Elipiu',26),
	 ('ELITELLINA','FGS','Elitellina',26);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'ELK','ELK Airways',12),
	 ('GEMSTONE','JEM','Emerald Airways',17),
	 ('TESTER','ETP','Empire Test Pilots School',17),
	 ('ENIMEX','ENI','Enimex',12),
	 (NULL,'QQQ','ENTERair',39),
	 ('EPAG','IAG','EPAG Groupe Air France',16),
	 ('ERFOTO','ERF','Erfoto',40),
	 ('ARE AVIACION','CTV','Escuela De Pilotos Are Aviacion',13),
	 ('ELISERVIZI','ESI','ESI Eliservizi Italiani',26),
	 ('ESTONIAN','ELL','Estonian Air',12);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('ELCO ETI','MJM','Eti 2000',26),
	 ('EUROAIRWAYS','EUY','EU Airways',23),
	 ('UNION JET','EUJ','EUjet',23),
	 ('EURAVIATION','EVN','Euraviation',26),
	 ('EURO CONTINENTAL','ECN','Euro Continental AIE',13),
	 (NULL,'EHM','Euro Harmony',40),
	 ('EUROSTAR','EUP','Euroair',20),
	 ('EUROATLANTIC','MMZ','EuroAtlantic Airways',40),
	 ('ECHELON','ECY','Euroceltic Airways',17),
	 (NULL,'EUC','Eurocontrol',5);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('EUROCOPTER','ECF','Eurocopter',16),
	 ('E-FLY','EEZ','Eurofly',26),
	 ('EUROFLY','EEU','Eurofly Service',26),
	 ('GOJET','GOJ','EuroJet Aviation',17),
	 ('JET ITALIA','ERJ','Eurojet Italia',26),
	 ('JET LINE','JLN','Eurojet Limited',36),
	 ('JET-ARROW','RDP','Eurojet Romania',41),
	 ('EEJAY SERVICE','EJS','Eurojet Servis',9),
	 ('EUROLOT','ELO','Eurolot',39),
	 ('EUROMANX','EMX','Euromanx Airways',3);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('LANGUEDOC','GED','Europe Air Lines',16),
	 ('FRENCH POST','FPO','Europe Airpost',16),
	 (NULL,'EU9','Europe Jet',16),
	 ('FIESTA','EUT','European 2000 Airlines',36),
	 (NULL,'EAG','European Aeronautical Group UK',17),
	 ('STAR WING','EAL','European Air Express',10),
	 ('EUROTRANS','BCS','European Air Transport',5),
	 ('EUROCHARTER','EAF','European Aviation Air Charter',17),
	 (NULL,'EBJ','European Business Jets',17),
	 ('COASTAL CLIPPER','ECB','European Coastal Airlines',21);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('EURO EXEC','ETV','European Executive',17),
	 ('ECHO EXPRESS','EXC','European Executive Express',44),
	 ('EuropeSky','EUV','EuropeSky',10),
	 ('EUROSENSE','EBG','Eurosense',6),
	 ('CATFISH','ESX','Euroskylink',17),
	 ('EUROWINGS','EWG','Eurowings',10),
	 ('AGENCY','EMN','Examiner Training Agency',17),
	 ('EXPO','XLA','Excel Airways',17),
	 ('HELI EXCEL','XEL','Excel Charter',17),
	 ('EXCELLENT AIR','GZA','Excellent Air',10);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AVCON','VCN','Execujet Charter',8),
	 ('VAMPIRE','VMP','Execujet Scandinavia',11),
	 ('ECHO','ECS','Executive Aircraft Charter and Charter Services',23),
	 (NULL,'XAH','Executive Aircraft Services',17),
	 ('SACAIR','EXU','Executive Airlines',13),
	 ('JESTER','JTR','Executive Aviation Services',17),
	 (NULL,'EXJ','Executive Jet Charter',17),
	 ('EXIN','EXN','Exin',39),
	 ('SKYMAN','JTM','Exxavia Limited',23),
	 ('RED ANGLE','IFA','FAI Airservice',10);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('FAIRLINE','FLS','Fairlines',37),
	 ('FAIROAKS','FFC','Fairoaks Flight Centre',17),
	 ('FALCAIR','FAR','Falcon Air',45),
	 ('FALCON','FCN','Falcon Air',44),
	 ('FALCONJET','FJC','Falcon Jet Centre',17),
	 ('BLUE STRIP','FAH','Farnair Hungary',22),
	 ('FARNED','FRN','Farnair Netherlands',37),
	 ('FARNER','FAT','Farnair Switzerland',8),
	 ('HELIBLUE','HBL','Faroecopter',11),
	 ('ROCKROSE','RCK','Faroejet',15);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('FINDON','FHL','Fast Helicopters',17),
	 ('FEDERAL AIRLINES','FLL','Federal Airlines',44),
	 ('DIPLOMATIC CLEARANCE','DCN','Federal Armed Forces',10),
	 ('FERIA','FER','Feria Aviacion',13),
	 ('FINISTAIR','FTR','Finist air',16),
	 (NULL,'FN1','Finlandian',14),
	 ('FINNAIR','FIN','Finnair',14),
	 ('WESTBIRD','WBA','Finncomm Airlines',14),
	 ('FINNFORCE','FNF','Finnish Air Force',14),
	 ('JETSET','FCA','First Choice Airways',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('FIRST CITY','MBL','First City Air',17),
	 ('FISCHER','FFR','Fischer Air',9),
	 ('FLYING FISH','FFP','Fischer Air Polska',39),
	 ('BROADWAY','BWY','Fleet Requirements Air Direction Unit',17),
	 ('FLEXY','FXY','Flexair',37),
	 (NULL,'FXT','Flexflight',11),
	 ('NAV CHECKER','FCK','Flight Calibration Service',10),
	 (NULL,'FDP','Flight Dispatch Services',39),
	 ('SPECAIR','LTS','Flight Inspections and Systems',43),
	 ('CALIBRATOR','CLB','Flight Precision Limited',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('FLIGHTSAFETY','FSL','Flight Safety Limited',17),
	 (NULL,'FSU','Flight Support Sweden',44),
	 ('CYGNET','AYR','Flight Training Europe',13),
	 ('FLIGHTLINE','FLT','Flightline',17),
	 ('FLIGHTPASS','FPS','Flightpass Limited',17),
	 ('KIEL AIR','FKI','FLM Aviation Mohrdieck',10),
	 ('QUICKFLOW','FLW','FLowair Aviation',16),
	 ('WITCHCRAFT','FFG','Flugdienst Fehlhaber',10),
	 ('ELEGANT','FVM','Flugfelag Vestmannaeyja',25),
	 ('YELLOW FLYER','FLU','Flugschule Basel',8);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('EICHENBURGER','EZB','Flugschule Eichenberger',8),
	 (NULL,'FWZ','Flugwerkzeuge Aviation Software',3),
	 ('DEALER','FCT','Fly CI Limited',17),
	 (NULL,'RWW','Fly Europa',13),
	 ('FLY EURO','FEE','Fly Europa Limited',17),
	 ('FLY EXCELLENT','FXL','Fly Excellent',44),
	 (NULL,'FRF','Fly France',16),
	 ('FLYLINE','FIL','Fly Line',13),
	 ('FLYBIRD','FLY','Fly Me Sweden',44),
	 (NULL,'FI5','Fly One',33);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('TENDER AIR','OTJ','Fly Romania',41),
	 ('FLYWEX','IAD','Fly Wex',26),
	 (NULL,'UKZ','Fly Zoom',17),
	 ('BABOO','BBO','Flybaboo',8),
	 ('JERSEY','BEE','Flybe',17),
	 ('FINNCOMM','FCM','Flybe Finland Oy',14),
	 ('FLYCOLUMBIA','FCE','Flycolumbia',13),
	 ('FLYCOM','FLO','Flycom',45),
	 ('BLUECRAFT','GVG','Flygaktiebolaget Gota Vingar',44),
	 ('GLOBESPAN','GSM','Flyglobespan',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'FPA','Flygprestanda',44),
	 ('EXTRANS','ETS','Flygtransporter I Nykoping',44),
	 ('INSTRUCTOR','INU','Flyguppdraget Backamo',44),
	 ('FLYHIRELAND','FHI','FlyHigh Airlines Ireland (FH)',23),
	 ('FLYING GROUP','FYG','Flying Service',5),
	 ('FLYING CENTER','FGP','Flying-Research Aerogeophysical Center',43),
	 ('Fast Jet','FYJ','FLYJET',39),
	 ('LITHUANIA AIR','LIL','FlyLal',29),
	 (NULL,'LLC','FlyLAL Charters',29),
	 ('FLYLINK','FLK','Flylink Express',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('NORDIC','NDC','FlyNordic',44),
	 ('FlyPortugal','FPT','FlyPortugal',40),
	 ('FLYTEAM','FTM','Flyteam Aviation',17),
	 ('HUSKY','FMG','FMG Verkehrsfliegerschule Flughafen Paderborn-Lippstadt',10),
	 (NULL,'FOP','Fokker',37),
	 ('FONNA','NOF','Fonnafly',38),
	 ('FRENCH AIR FORCE','FAF','Force Aerienne Francaise',16),
	 ('FORDAIR','FOB','Ford Motor Company',17),
	 ('FORMULA','FOR','Formula One Management',17),
	 ('HELISCOT','FHS','Forth and Clyde Helicopter Services',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('YEOMAN','JFY','Foster Yeoman',17),
	 ('FOTOGRAFIA','FTE','Fotografia F3',13),
	 ('WILDFOX','FXR','Foxair',26),
	 ('RUSHTON','FRA','FR Aviation',17),
	 ('FA','X9F','FRA Air',10),
	 ('FRENCH CUSTOM','FDO','France Douanes',16),
	 ('FRENCH NAVY','FNY','France Marine Nationale',16),
	 (NULL,'FOF','Fred. Olsen',38),
	 ('FREEWAY','FWC','Freeway Air',37),
	 ('WILDGOOSE','FAE','Freshaer',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('FINNGUARD','FNG','Frontier Guard',14),
	 ('SEABIRD','FSB','FSB Flugservice & Development',10),
	 ('LEIPZIG FAIR','LEJ','FSH Luftfahrtunternehmen',10),
	 (NULL,'FTI','FTI Fluggesellschaft',10),
	 ('FAASA','FAM','Fumigacion Aerea Andaluza',13),
	 ('REGO','ROG','Fundaci� Rego',13),
	 ('Applewood','FGL','Futura Gael',23),
	 ('FUTURA','FUA','Futura International Airways',13),
	 ('BATMAN','EXH','G5 Executive',10),
	 ('GAMHELICO','GAH','Ga-Ma Helicoptere',16);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('GADAIR','GDR','Gadair European Airlines',13),
	 ('HERCULES JET','GNJ','Gain Jet Aviation',20),
	 ('GALAIR','SWF','Galair International',17),
	 ('GALS','GLS','Galaircervis',48),
	 ('GAMA','GMA','Gama Aviation',17),
	 ('GAMISA','GMJ','Gamisa Aviacion',13),
	 ('Gandalf','GNF','Gandalf Airlines',26),
	 ('GAVINA','GVN','Gavina',13),
	 ('GAZPROMAVIA','GZP','Gazpromavia',43),
	 ('GEEBEE AIRWAYS','GBL','GB Airways',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('FERRANTI','FFU','GEC Marconi Avionics',17),
	 ('GECAS','GCC','GECAS',23),
	 ('BELGIAN GENERMERIE','GDB','Gendarmerie Belge',5),
	 ('FRANCE GENDARME','FGN','Gendarmie Nationale',16),
	 ('GONZO','GNZ','General Aviation',39),
	 (NULL,'GNX','Genex',7),
	 ('GERMAN AIR FORCE','GAF','German Air Force',10),
	 ('FLB','FLB','German Air Force - FLB',10),
	 ('GERMAN ARMY','GAM','German Army',10),
	 (NULL,'GER','German International Air Lines',10);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('GERMAN NAVY','GNY','German Navy',10),
	 ('GERMAN SKY','GHY','German Sky Airlines',10),
	 ('GERMANIA','GMI','Germania',10),
	 ('GERMAN WINGS','GWI','Germanwings',10),
	 (NULL,'GXG','GermanXL',10),
	 ('KITE','GFD','Gesekkschaft Fur Flugzieldarstellung',10),
	 ('GESTAIR','GES','Gestair',13),
	 ('BANJET','GJT','Gestion Aerea Ajecutiva',13),
	 (NULL,'GHI','GH Stansted Limited',17),
	 ('GLOBAL AUSTRIA','GLJ','Global Jet Austria',3);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SILVER ARROWS','SVW','Global Jet Luxembourg',30),
	 ('JET LIFT','GSS','Global Supply Systems',17),
	 (NULL,'GLP','Globus',43),
	 ('GEE-EM HELICOPTERS','GMG','GM Helicopters',31),
	 ('Go Flight','GOE','Go Fly (United Kingdom)',17),
	 ('RELAX','RLX','Go2Sky',46),
	 (NULL,'GOD','GoDutch',37),
	 ('SWISS HAWK','GOI','Gofir',8),
	 ('AIR PARTNER','GDA','GoldAir',17),
	 ('GOLDECK FLUG','GDK','Goldeck-Flug',3);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('GOLDEN','GAO','Golden Air',44),
	 ('GOMEL','GOM','Gomel Airlines',7),
	 ('RED STAR','RDR','Goodridge (UK) Limited',17),
	 ('GORLITSA','GOR','Gorlitsa Airlines',48),
	 ('GRANITE','HLD','Grampian Flight Centre',17),
	 ('GRANAVI','GAV','Granada Aviacion',13),
	 (NULL,'GCA','Grand Cru Airlines',29),
	 ('LANDMARK','LMK','Grantex Aviation',17),
	 ('HELLENIC NAVY','HNA','Greek Navy',20),
	 (NULL,'GFY','Greenfly',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('GRIXONA','GXA','Grixona',33),
	 ('GRIZODUBOVA AIR','GZD','Grizodubova Air Company',43),
	 ('GROSSMANN','HTG','Grossmann Air Service',3),
	 ('GROSSJET','GSJ','Grossmann Jet Service',9),
	 ('GRUPOMED','GPM','Grup Air-Med',13),
	 ('VUELOS MED','VMM','Grupo Vuelos Mediterraneo',13),
	 ('GUARD AIR','GSY','Guard Systems',38),
	 (NULL,'GU1','Gulisano airways',26),
	 ('GWYN','GWN','Gwyn Aviation',17),
	 ('AIRNET','POW','Hagondale Limited',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('ROOSTER','HHN','Hahn Air',10),
	 (NULL,'HAY','Hamburg Airways',10),
	 ('HAMBURG JET','HHI','Hamburg International',10),
	 ('BIZJET','HJL','Hamlin Jet',17),
	 ('HANG','HGR','Hangar 8',17),
	 ('HAPAG LLOYD','HLF','Hapagfly',10),
	 ('NORBROOK','NBR','Haughey Air',17),
	 ('POYSTON','PYN','Haverfordwest Air Charter Services',17),
	 ('HEAVYLIFT','HLA','HC Airlines',17),
	 ('Hebradran','HBR','Hebradran Air Services',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('HELICATALUNA','HDC','Helcopteros De Cataluna',13),
	 ('HELENIA','HHP','Helenia Helicopter Service',11),
	 ('HELI BULGARIA','HLR','Heli Air Services',6),
	 ('ALPIN HELI','ALJ','Heli Ambulance Team',3),
	 ('HELIBERNINA','HEB','Heli Bernina',8),
	 ('HELIFRANCE','HFR','Heli France',16),
	 ('AIR RED','RWZ','Red Wings',43),
	 ('HELIHUNGARY','HYH','Heli Hungary',22),
	 ('HELI SAINT-TROPEZ','HLI','Heli Securite',16),
	 ('HELI UNION','HLU','Heli Union Heli Prestations',16);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('HELI HOLLAND','HHE','Heli-Holland',37),
	 ('ERICA','HRA','Heli-Iberica',13),
	 ('HIFSA','HIF','Heli-Iberica Fotogrametria',13),
	 ('INTER GUYANNE','HIG','Heli-Inter Guyane',16),
	 ('HELI-LINK','HLK','Heli-Link',8),
	 ('HELIAVIA','HEA','Heliavia-Transporte Aereo',40),
	 ('CADDY','CDY','Heliaviation Limited',17),
	 ('HELIBRAVO','HIB','Helibravo Aviacao',40),
	 ('HELICAP','HLC','Helicap',16),
	 ('HELICENTRE','COV','Helicentre Coventry',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('HELI CZECH','HCP','Helicopter',9),
	 ('JOCKEY','JKY','Helicopter & Aviation Services',17),
	 ('MAVRIK','MVK','Helicopter Training & Hire',17),
	 ('HELICSA','HHH','Helicsa',13),
	 ('HELIDRIFT','HDR','Helikopterdrift',38),
	 ('SWEDCOPTER','SCO','Helikopterservice Euro Air',44),
	 ('HELIOCEAN','OCE','Heliocean',16),
	 ('HELIPISTAS','HLP','Helipistas',13),
	 ('HELIPORTUGAL','HPL','Heliportugal',40),
	 ('HELIS','HSU','Helisul',40);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('HELISWISS','HSI','Heliswiss',8),
	 ('HELITALIA','HIT','Helitalia',26),
	 ('SCANBIRD','HTA','Helitrans',38),
	 (NULL,'HTH','Helitt L�neas A�reas',13),
	 ('HELLAS JET','HEJ','Hellas Jet',20),
	 ('HELLENIC AIR FORCE','HAF','Hellenic Air Force',20),
	 ('Hellenic','HEY','Hellenic Airways',20),
	 ('IMPERIAL','IMP','Hellenic Imperial Airways',20),
	 ('Hellenic Star','HST','Hellenic Star Airways',20),
	 ('FLYHELLO','FHE','Hello',8);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('HELOG','HLG','Helog',8),
	 ('HELVETIC','OAW','Helvetic Airways',8),
	 ('HEMUS AIR','HMS','Hemus Air',6),
	 ('HERMES','HRM','Hermes Airlines',20),
	 ('FLAPJACK','HED','Herritage Aviation Developments',17),
	 ('HEX AIRLINE','HER','Hex Air',16),
	 ('SKY FLYER','HFY','Hi Fly',40),
	 ('HIWAY','HWY','Highland Airways',17),
	 ('HOLA','HOA','Hola Airlines',13),
	 (NULL,'HCC','Holidays Czech Airlines',9);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('HOLSTEN','HTR','Holstenair Lubeck',10),
	 ('HOMAC','HMV','Homac Aviation',30),
	 (NULL,'OME','Homer Air',10),
	 ('HORIZON','HOR','Horizon Air-Taxi',8),
	 ('GREGG AIR','GGV','Houston Jet Services',3),
	 ('FLITEWISE','HWD','HPM Investments',17),
	 ('COPTER TRANS','KTR','HT Helikoptertransport',44),
	 ('HELIAPRA','AHT','HTA Helicopteros',40),
	 ('SILVER EAGLE','HUV','Hunair Hungarian Airlines',22),
	 ('HUNGARIAN AIRFORCE','HUF','Hungarian Air Force',22);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('RUSSIAN SKY','RSY','I-Fly',43),
	 ('IBERIA','IBE','Iberia Airlines',13),
	 (NULL,'IBS','Iberia Express',13),
	 ('IBERTOUR','IBR','Ibertour Servicios Aereos',13),
	 ('IBERTRANS','IBT','Ibertrans Aerea',13),
	 (NULL,'IWD','Iberworld',13),
	 ('IBICENCA','IBC','Ibicenca Air',13),
	 ('BLUE','BBL','IBM Euroflight Operations',8),
	 ('TUZLA AIR','RAC','Icar Air',4),
	 ('FRANCHE COMPTE','FRC','Icare Franche Compte',16);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('ICARFLY','ICA','Icaro',26),
	 ('ICARUS','IUS','Icarus',26),
	 ('ICEBIRD','ICB','Icebird Airline',25),
	 ('ICEJET','ICJ','Icejet',25),
	 ('ICEAIR','ICE','Icelandair',25),
	 ('ICELAND COAST','ICG','Icelandic Coast Guard',25),
	 ('INDIGO','IDG','IDG Technology Air',9),
	 ('FLIGHT RED','RDE','II Lione Alato Arl',17),
	 ('JET MANAGEMENT','IJM','IJM International Jet Management',3),
	 ('IKAROS','IKR','Ikaros DK',11);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('IKON','IKN','IKON FTO',10),
	 ('CIOCCO','CIO','Il Ciocco International Travel Service',26),
	 ('ILAVIA','ILV','Il-Avia',43),
	 ('ILYICHAVIA','ILL','Ilyich-Avia',48),
	 ('IMAER','IMR','Imaer',40),
	 ('INDICATOR','IDR','Indicator Company',22),
	 ('TITANLUX','ITN','Industrias Titan',13),
	 ('INFINIT','FFI','Infinit Air',13),
	 (NULL,'INS','Inflite The Jet Centre',17),
	 ('CARTO','ICC','Instituto Cartografico de Cataluna',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'FFL','Intavia Limited',17),
	 ('INTER WINGS','ITW','Inter Air',6),
	 (NULL,'IEA','Inter European Airways',17),
	 ('ASTAIR','SUW','Interavia Airlines',43),
	 ('INTERAVIA','IVT','Interaviatrans',48),
	 ('CHOPER','ICP','Intercopters',13),
	 ('INTERFLIGHT','IFT','Interflight',17),
	 (NULL,'IJT','Interflight (Learjet)',17),
	 ('INFLY','RFL','Interfly',26),
	 ('INTERJET','MTF','Interjet',26);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('INTERCOPTER','IHE','Interjet Helicopters',20),
	 (NULL,'ITC','International Air Carrier Association',5),
	 ('INTERBIZ','IBZ','International Business Air',44),
	 ('RED CROSS','RED','International Committee of the Red Cross',8),
	 (NULL,'INE','International Europe',13),
	 (NULL,'ISF','International Sabilisation Assistance Force',17),
	 ('INTERSKY','ISK','Intersky',3),
	 ('GENERAL SKY','IKY','Intersky',6),
	 ('FREEWAYAIR','FWA','Interstate Airline',37),
	 ('INVER','INV','Inversija',31);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('IONA','IND','Iona National Airways',23),
	 ('SHIPEX','IPM','IPM Europe',17),
	 ('IRISH','IRL','Irish Air Corps',23),
	 ('IRISH TRANS','RDK','Irish Air Transport',23),
	 ('AUTHORITY','XMR','Irish Aviation Authority',23),
	 ('ISDAVIA','ISD','ISD Avia',48),
	 ('ISLE AVIA','IOM','Island Aviation and Travel',17),
	 (NULL,'ISX','Island Spirit',25),
	 ('JARLAND','IAJ','Islandair Jersey',17),
	 ('PINTADERA','ISW','Islas Airways',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SCILLONIA','IOS','Isles of Scilly Skybus',17),
	 ('ITALI','ACL','Itali Airlines',26),
	 ('RIVIERA','IFS','Italy First',26),
	 (NULL,'FDF','IVV Femida',43),
	 ('X-BIRD','IXR','Ixair',16),
	 ('IZHAVIA','IZA','Izhavia',43),
	 ('JAYSEEBEE','JCB','J C Bamford (Excavators)',17),
	 ('JAT','JAT','Jat Airways',42),
	 (NULL,'JRB','Jc royal.britannica',17),
	 ('JAY DEE','JDA','JDAviation',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('RED PELICAN','JDP','JDP Lux',30),
	 ('JETPLAN','JPN','Jeppesen UK',17),
	 ('JETA','JEA','Jet Air',39),
	 ('SISTEMA','JSI','Jet Air Group',43),
	 ('JETAVIATION','PJS','Jet Aviation',8),
	 ('JET CENTER','JCF','Jet Center Flight Training',13),
	 ('JET CONNECT','JCX','Jet Connection',10),
	 ('JET EXECUTIVE','JEI','Jet Executive International Charter',10),
	 ('MOLDJET','MJL','Jet Line International',33),
	 ('JEDI','JDI','Jet Service',39);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('JET STREAM','JSM','Jet Stream',33),
	 ('MOSCOW JET','JTT','Jet-2000',43),
	 ('CHANNEX','EXS','Jet2.com',17),
	 ('BEAUTY','JAF','Jetairfly',5),
	 ('JETALLIANCE','JAG','Jetalliance',3),
	 ('JETCLUB','JCS','Jetclub',8),
	 ('JETFLITE','JEF','Jetflite',14),
	 ('LINEFLYER','JFL','Jetfly Airlines',3),
	 (NULL,'JLH','Jetlink Holland',37),
	 ('JET MAGIC','JMG','JetMagic',23);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('JETNOVA','JNV','Jetnova de Aviacion Ejecutiva',13),
	 ('JETRAN AIR','MDJ','Jetran Air',41),
	 ('JETRIDER','JRI','Jetrider International',17),
	 ('JET PERSONALES','JEP','Jets Personales',13),
	 ('STREAM-AIR','JSH','Jetstream Air',22),
	 ('VANNIN','JXT','Jetstream Executive Travel',17),
	 ('JETTIME','JTG','Jettime',11),
	 ('JETBIRD','JXX','Jetx Airlines',25),
	 ('JIGSAW','JSW','Jigsaw Project',17),
	 ('JAYEMMSEE','JMC','JMC Airlines',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('LADYBLUE','JDG','Joanas Avialinijos',29),
	 ('JOBAIR','JBR','Job Air',9),
	 ('ISLANDIC','JVK','Jorvik',25),
	 ('ENZO','ENZ','Jota Aviation',17),
	 ('JUNKERS','JUR','Ju-Air',8),
	 ('DUKE','DKE','Jubilee Airways',17),
	 ('MELODY','MEY','Justair Scandinavia',44),
	 ('SKY CAMEL','KSA','K S Avia',31),
	 (NULL,'KAR','Kar-Air',14),
	 ('AVIAKARAT','AKT','Karat',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('KARLOG','KLG','Karlog Air Charter',11),
	 ('KATEKAVIA','KTK','Katekavia',43),
	 ('KATO-AIR','KAT','Kato Airline',38),
	 ('AIR MINVODY','MVD','Kavminvodyavia',43),
	 ('KAZAVAIA','KAO','Kazan Aviation Production Association',43),
	 ('KAMA','KPH','Kazan Helicopters',43),
	 ('KALININGRAD AIR','KNI','KD Avia',43),
	 ('KEENAIR','JFK','Keenair Charter -',17),
	 (NULL,'KHK','Kharkiv Airlines',48),
	 ('WEST-KHARKOV','WKH','Kharkov Aircraft Manufacturing Company',48);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('KHORIV-AVIA','KRV','Khoriv-Avia',48),
	 ('AIRCOMPANY KHORS','KHO','Khors Aircompany',48),
	 ('AVIATION PLANT','UAK','Kiev Aviation Plant',48),
	 ('KING','KNG','King Aviation',17),
	 ('KINLOSS','KIN','Kinloss Flying Training Unit',17),
	 ('KINNARPS','KIP','Kinnarps',44),
	 ('VYATKA-AVIA','KTA','Kirov Air Enterprise',43),
	 ('CITY','KLC','KLM Cityhopper',37),
	 ('KLM HELI','KLH','KLM Helicopter',37),
	 ('KLM','KLM','KLM Royal Dutch Airlines',37);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('KOANDA','KOA','Koanda Avacion',13),
	 ('KOGALYM','KGL','Kogalymavia Air Company',43),
	 ('COMJET','KOM','Kom Activity',37),
	 ('KOMI AVIA','KMA','Komiaviatrans State Air Enterprise',43),
	 ('KOMIINTER','KMV','Komiinteravia',43),
	 ('KNAAPO','KNM','Komsomolsk-on-Amur Air Enterprise',43),
	 ('AUTOFLEX','KOB','Koob-Corp - 96 KFT',22),
	 ('KOSMAS CARGO','KMG','Kosmas Air',42),
	 ('KOSMOS','KSM','Kosmos',43),
	 ('KOSOVA','KOS','Kosova Airlines',42);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'KOQ','Kostromskie avialinii',43),
	 ('WOKAIR','WOK','Kovar Air',9),
	 ('KRASNOJARSKY AIR','KJC','Krasnojarsky Airlines',43),
	 ('KREMENCHUK','KFC','Kremenchuk Flight College',48),
	 ('AVIAMONTAG','KRG','Krimaviamontag',48),
	 ('KROONK','KRO','Kroonk Air Agency',48),
	 ('Krylo','KRI','Krylo Airlines',43),
	 ('CRIMEA AIR','KYM','Krym',48),
	 ('OPTIC','OPC','Krystel Air Charter',17),
	 ('KSY','KSY','KSY',20);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AIR KUBAN','KIL','Kuban Airlines',43),
	 (NULL,'KZA','Kurzemes Avio',43),
	 ('SWECOAST','KBV','Kustbevakningen',44),
	 ('LADY RACINE','LRB','L R Airlines',9),
	 ('PHOTOFLIGHT','PHO','L&L Flygbildteknik',44),
	 (NULL,'JEV','Lagun Air',13),
	 ('ISLANDIA','ISL','Landsflug',25),
	 ('PROFLIGHT','PAP','Langtry Flying Group',17),
	 ('AEROLANZA','LZA','Lanza Air',13),
	 ('BARAKA','LZT','Lanzarote Aerocargo',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('LATCHARTER','LTC','LatCharter',31),
	 ('LATVIAN AIRFORCE','LAF','Latvian Air Force',31),
	 ('LAUDA AIR','LDA','Lauda Air',3),
	 ('LAUDA ITALY','LDI','Lauda Air Italy',26),
	 ('LAUS AIR','LSU','Laus',21),
	 (NULL,'LMM','LCM AIRLINES',43),
	 ('JAVELIN','LEE','Leeming Flying Training Unit',17),
	 ('LEONAVIA','LEL','Leonsa De Aviacion',13),
	 (NULL,'LIQ','Lid Air',44),
	 ('Bluebird','LBL','Line Blue',10);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AEROLAIRE','ALR','Lineas Aereas Alaire S.L.',13),
	 ('LINTON ON OUSE','LOP','Linton-on-Ouse Flying Training Unit',17),
	 (NULL,'LIO','L�O Flugmennt',25),
	 ('WORLDGATE','WGT','Lion Air Services',17),
	 ('LIONSAIR','LEU','Lions-Air',8),
	 ('LITHUANIAN AIRFORCE','LYF','Lithuanian Air Force',29),
	 ('LIVINGSTON','LVG','Livingston',26),
	 ('ELNAIR','LNA','Lnair Air Services',13),
	 ('LOGAN','LOG','Logan Air',17),
	 ('AEROTRAINING','CLV','Lom Praha Flying School',9);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('LOMAS','LMS','Lomas Helicopters',17),
	 ('LONDON CITY','LCY','London City Airport Jet Centre',17),
	 ('LONEX','LNX','London Executive Aviation',17),
	 ('LOVEAIR','LOV','London Flight Centre (Stansted)',17),
	 ('MUSTANG','LHC','London Helicopter Centres',17),
	 ('LORRAINE','LRR','Lorraine Aviation',16),
	 ('LOSSIE','LOS','Lossiemouth Flying Training Unit',17),
	 ('POLLOT','LOT','LOT Polish Airlines',39),
	 ('slowbird','LOO','LSM Airlines',43),
	 ('Moscow frog ','YZZ','LSM AIRLINES ',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('moose','UWW','LSM International ',43),
	 ('FUN JET','LTE','LTE International Airways',13),
	 ('BILLA TRANSPORT','LTO','LTU Austria',3),
	 ('LTU','LTU','LTU International',10),
	 ('russian sky','LJJ','Luchsh Airlines ',43),
	 ('TWENTAIR','LTW','Luchtvaartmaatschappij Twente',37),
	 ('AIR SANTE','LVD','Luftfahrt-Vermietungs-Dienst',3),
	 ('WALTER','LGW','Luftfahrtgesellschaft Walter',10),
	 ('LUFTHANSA','DLH','Lufthansa',10),
	 ('LUFTHANSA CARGO','GEC','Lufthansa Cargo',10);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('HANSALINE','CLH','Lufthansa CityLine',10),
	 ('LUFTHANSA TECHNIK','LHT','Lufthansa Technik',10),
	 ('Garfield','LTF','Lufttaxi Fluggesellschaft',10),
	 ('LUFT TRANSPORT','LTR','Lufttransport',38),
	 ('ENTERPRISE LUHANSK','LHS','Luhansk',48),
	 ('LUKOIL','LUK','LUKoil-Avia',43),
	 ('UNIVERSITY','UNY','Lund University School of Aviation',44),
	 ('LUXAIR','LGL','Luxair',30),
	 ('RED LION','LXA','Luxaviation',30),
	 ('LUX RESCUE','LUV','Luxembourg Air Rescue',30);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('LUX EXPRESS','LFE','Luxflight Executive',30),
	 ('LISBON JET','LUZ','Luzair',40),
	 ('UKRAINE WEST','UKW','Lviv Airlines',48),
	 ('LYDDAIR','LYD','Lydd Air',17),
	 ('MAC AVIATION','MAQ','Mac Aviation',13),
	 ('MAC FOTO','MCF','MAC Fotografica',13),
	 ('MACAIR','MCS','Macedonian Airlines',20),
	 ('MAGIC BLUE','MJB','Magic Blue Airlines',37),
	 ('MAGNA AIR','MGR','Magna Air',3),
	 ('AEROKEY','MKK','Malaya Aviatsia Dona',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('MALEV','MAH','Mal�v',22),
	 ('MALI AIREXPRESS','MAE','Mali Air',3),
	 ('SCANWING','SCW','Malmo Aviation',44),
	 ('Scanwings','SCW','Malm� Aviation',44),
	 ('LOGIC','LOD','Malmoe Air Taxi',44),
	 ('MALTA CHARTER','MAC','Malta Air Charter',36),
	 ('MALTA WINGS','MWS','Malta Wings',36),
	 ('MANAG''AIR','MRG','MANAG AIR',16),
	 ('MANHATTAN','MHN','Manhattan Air',17),
	 ('TEEMOL','MNR','Mann Air',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('MANX','MNX','Manx Airlines',17),
	 ('MAPJET','MPJ','MAP-Management and Planung',3),
	 ('MARCH','MAR','March Helicopters',17),
	 ('MARHAM','MRH','Marham Flying Training Unit',17),
	 ('GOSHAWK','MKO','Markoss Aviation',17),
	 ('AVIAMARS','MRW','Mars RK',48),
	 ('MARSHALL','MCE','Marshall Aerospace',17),
	 ('MARTIN','MBE','Martin-Baker',17),
	 ('MARTINAIR','MPH','Martinair',37),
	 ('SEAHORSE','MFA','Martyn Fiddler Associates',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('snowball','MRS','Marusya Airways',43),
	 ('MARVIN','MVN','Marvin Limited',17),
	 ('TRAFALGAR','TFG','MAS Airways',17),
	 ('MASTER AIRWAYS','MSW','Master Airways',42),
	 ('MASTERJET','LMJ','Masterjet',40),
	 ('Mavial','MVL','Mavial Magadan Airlines',43),
	 ('MAXAIR','MXL','Maxair',44),
	 ('CALSON','MCA','MCA Airlines',44),
	 ('MACLINE','MCH','McAlpine Helicopters',17),
	 ('MEDALS','MDP','Medallion Air',41);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('MEDAVIA','MDM','Medavia Company',36),
	 ('MEDIC','MCL','Medical Aviation Services',17),
	 ('MED-FREIGHT','MDF','Mediterranean Air Freight',20),
	 ('AIR POLTAVA','POV','Meridian',48),
	 ('DIESEL','DSL','Meridian Aviation',17),
	 ('MERIDIAN CHERRY','MEM','Meridian Limited',48),
	 ('MERAIR','ISS','Meridiana',26),
	 ('METMAN','MET','Meteorological Research Flight',17),
	 (NULL,'MVI','Metro Business Aviation',17),
	 ('METROPIX','PIX','Metropix UK',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('METRO REGIONAL','MPS','Metroplis',37),
	 ('MAG AVACION','MGA','MG Aviacion',13),
	 ('SALLINE','JLA','MIA Airlines',41),
	 (NULL,'BIB','Michelin Air Services',16),
	 ('WIZARD','WIZ','Micromatter Technology Solutions',17),
	 (NULL,'MID','Midland Airport Services',17),
	 ('MILLEN','RJM','Millen Corporation',17),
	 ('MIMINO','MIM','Mimino',43),
	 ('MINILINER','MNL','Miniliner',26),
	 ('LISLINE','LIR','Minsk Aircraft Overhaul Plant',7);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'MIC','Mint Airways',13),
	 ('MISIONAIR','MSN','Missionair',13),
	 ('MARIANNE','MRN','Missions Gouvernemtales Francaises',16),
	 ('AIRMERCI','MSA','Mistral Air',26),
	 ('MOLDAERO','MLE','Moldaeroservice',33),
	 ('MOLDAVIAN','MDV','Moldavian Airlines',33),
	 ('MOLDOVA-STATE','MVG','Moldova',33),
	 ('MONARCH','MON','Monarch Airlines',17),
	 ('MONDEAIR CARGO','MDB','Monde Air Charters',17),
	 ('MONTAIR','MGX','Montenegro Airlines',34);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('GROMOV AIRLINE','GAI','Moskovia Airlines',43),
	 ('MOTOR SICH','MSI','Motor Sich',48),
	 ('SKYRUNNER','EBF','MSR Flug-Charter',10),
	 ('MURMAN AIR','MNZ','Murmansk Aircompany',43),
	 ('FRANKY','MYW','My Way Airlines',26),
	 ('MYFLUG','MYA','Myflug',25),
	 ('VIKING','VKG','Mytravel Airways',11),
	 ('KESTREL','MYT','MyTravel Airways',17),
	 ('SHERLOCK','RFI','National Air Traffic Services',17),
	 ('GRID','GRD','National Grid',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('PANDER','NLS','Nationale Luchtvaartschool',37),
	 ('SCIENCE','EVM','Natural Environment Research Council',17),
	 ('NAV DISPATCH','NAV','Nav Flight Planning',9),
	 (NULL,'NVP','Navegacao Aerea De Portugal',40),
	 ('NAYSA','NAY','Navegacion Servicios Aereos Canarios SA',13),
	 ('NETHERLANDS COASTGUARD','NCG','Nederlandse Kustwacht',37),
	 ('NEFTEAVIA','NFT','Nefteyugansk Aviation Division',43),
	 ('MOONFLOWER','NOS','Neos',26),
	 ('NERICAIR','NSL','Neric',17),
	 ('NEXTJET','NTJ','NextJet',44);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('EXECUTIVE','EXT','Night Express',10),
	 ('FLYNIKI','NLY','Niki',3),
	 ('AIR NIKOLAEV','NKV','Nikolaev-Air',48),
	 ('NIMBUS','NBS','Nimbus Aviation',17),
	 ('VARTOSKAVIA','NVK','Nizhnevartovskavia',43),
	 ('NORTHOLT','NOH','No. 32 (The Royal) Squadron RAF',17),
	 ('NOBIL AIR','NBL','Nobil Air',33),
	 (NULL,'NOC','Norcopter',38),
	 ('NORDEX','NEF','Nord-Flyg',44),
	 ('Nordic Global','NGB','Nordic Global Airlines',14);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('NORTH RIDER','NRD','Nordic Regional',44),
	 ('NORDVIND','NVD','Nordic Solutions',29),
	 ('NORDLAND','NWS','NordWind Airlines',43),
	 ('NORESTAIR','NRT','Norestair',13),
	 ('COUNTY','NCF','Norfolk County Flight College',17),
	 ('NORLAND','FNA','Norlandair',25),
	 ('LIFEGUARD SWEDEN','HMF','Norrlandsflyg',44),
	 ('NORSEMAN','NIR','Norsk Flyrjeneste',38),
	 ('NORSKE','NOR','Norsk Helikopter',38),
	 ('HELIDOC','DOC','Norsk Luftambulanse',38);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('TIC-TAC','RTV','Nortavia',40),
	 ('NORTH-ADRIA','NAI','North Adria Aviation',21),
	 ('NORTH ATLANTIC','NFC','North Atlantic Cargo',38),
	 ('TEESAIR','NBN','North British Airlines',17),
	 ('NORTH FLYING','NFA','North Flying',11),
	 ('NORTH SEA','NRC','North Sea Airways',37),
	 ('VYBORG AIR','VBG','North-West Air Transport Company - Vyborg',43),
	 ('NORTON','NSF','Northamptonshire School of Flying',17),
	 ('NEATAX','NEX','Northern Executive Aviation',17),
	 ('NORTHUMBRIA','NHL','Northumbria Helicopters',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'NWO','Northwood Headquarters (RAF',17),
	 ('NORTRANS','IBK','Norwegian Air International (D8)',38),
	 ('NOR SHUTTLE','NAX','Norwegian Air Shuttle',38),
	 ('SPRIT','TFN','Norwegian Aviation College',38),
	 ('NORSTAR','NLH','Norwegian Long Haul AS',38),
	 ('NAVIGATOR','NVR','Novair',44),
	 ('SADKO AVIA','NVG','Novogorod Air Enterprise',43),
	 ('NARPAIR','NSP','Novosibirsk Aircraft Repairing Plant',43),
	 ('NAKAIR','NBE','Novosibirsk Aviaenterprise',43),
	 ('NOVSIB','NPO','Novosibirsk Aviation Production Association',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'NFD','N�rnberger Flugdienst',10),
	 ('O-BIRD','OCN','O Air',16),
	 ('OCEANCARGO','VCX','Ocean Airlines',26),
	 ('OCEANSKY','OCS','Ocean Sky (UK)',17),
	 ('ODESSA AIR','ODS','Odessa Airlines',48),
	 ('FOCA','FOC','Office Federal De''Aviation Civile',8),
	 ('OLIMEX','OLX','Olimex Aerotaxi',9),
	 ('OLYMPIC','OAL','Olympic Airlines',20),
	 ('OLAVIA','OLY','Olympic Aviation',20),
	 ('OMNI','OAV','Omni - Aviacao e Tecnologia',40);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('OMSK','OMS','Omskavia Airline',43),
	 ('MISTRAL','BOS','OpenSkies',17),
	 ('ORBEST','OBS','Orbest',40),
	 ('BLUELIGHT','BUE','Orebro Aviation',44),
	 ('ORPRISE','ORM','Orel State Air Enterprise',43),
	 ('ORENBURG','ORB','Orenburg Airlines',43),
	 (NULL,'ORG','Orenburzhie',43),
	 ('ORIONIX','OIX','Orion-x',43),
	 ('ORANGE','RNG','Ornage Aircraft Leasing',37),
	 ('AIR COLLEGE','OCO','Ostend Air College',5);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('OLTRA','OLT','Ostfriesische Lufttransport',10),
	 ('FINN FLIGHT','FNL','Oulun Tilauslento',14),
	 ('OXOE','OXE','Oxaero',17),
	 ('WOODSTOCK','WDK','Oxford Air Services',17),
	 ('PAISAJES','PAE','Paisajes Espanoles',13),
	 ('PAKKER AVIO','PKR','Pakker Avio',12),
	 ('PALMER','JSP','Palmer Aviation',17),
	 ('SKYJET','PNR','PAN Air',13),
	 (NULL,'PEA','Pan Europeenne Air Service',16),
	 ('PANAMEDIA','PEI','Panamedia',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('KUBAN LIK','PNH','Panh',43),
	 ('PANNON','PHU','Pannon Air Service',22),
	 ('PANORAMA','PNM','Panorama',13),
	 (NULL,'PGF','Paragon Global Flight Support',17),
	 ('BYTE','BYT','Patriot Aviation Limited',17),
	 ('GOLDCREST','KGC','Peach Air',17),
	 ('PECOTOX','PXA','Pecotox Air',33),
	 ('PEGAVIATION','PEV','Pegasus Aviation',20),
	 ('HELIFALCON','HAK','Pegasus Helicopters',38),
	 ('PENDLEY','PDY','Pen-Avia',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('PENA DEL AIRE','PCA','Penya De L''Aire',13),
	 ('PERM AIR','PGP','Perm Airlines',43),
	 ('PETROKAM','PTK','Petropavlovsk-Kamchatsk Air Enterprise',43),
	 ('NEW BIRD','PHV','Phenix Aviation',16),
	 ('PHILAIR','PHI','Philips Aviation Services',37),
	 ('PHOENIX','PAM','Phoenix Air Service',10),
	 ('PILATUS WINGS','PCH','Pilatus Flugzeugwerke',8),
	 ('Pim Air','PHJ','Pim Air',37),
	 ('PRINAIR EXPRESS','PRN','Pirinair Express',13),
	 ('OSPREY','PDG','PLM Dollar Group',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('LIBELLE','LIB','Ploizeihubschrauberstaffel Hamburg',10),
	 ('LIZARD','PSF','Plymouth School of Flying',17),
	 ('POBEDA','PBD','Pobeda',43),
	 ('PODILIA','PDA','Podilia-Avia',48),
	 ('POLESTAR','PSR','Polestar Aviation',17),
	 ('POLET','POT','Polet',43),
	 ('AIRPOL','POF','Police Aux Frontiers',16),
	 ('SPECIAL','PLC','Police Aviation Services',17),
	 ('POLISH AIRFORCE','PLF','Polish Air Force',39),
	 ('POLISH NAVY','PNY','Polish Navy',39);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('HUMMEL','NRW','Polizeifliegerstaffel Nordrhein-Westfalen',10),
	 ('POLICE PHOENIX','PPH','Polizeihibschrauberstaffel Neidersachsen',10),
	 ('POLICE IKARUS','PIK','Polizeihuberschrauberstaffel Sachsen-Anhalt',10),
	 ('SPERBER','SRP','Polizeihubschrafterstaffel Rheinland-Pfalz',10),
	 ('BUSSARD','PBW','Polizeihubschrauberstaffel Baden-Wurtemberg',10),
	 ('POLICE EDELWEISS','EDL','Polizeihubschrauberstaffel Bayern',10),
	 ('ADEBAR','PBB','Polizeihubschrauberstaffel Brandenburg',10),
	 ('IBIS','PHH','Polizeihubschrauberstaffel Hessen',10),
	 ('POLICE MERLIN','PMV','Polizeihubschrauberstaffel Mecklenburg-Vorpommern',10),
	 ('PASSAT','PHS','Polizeihubschrauberstaffel Sachsen',10);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('HABICHT','HBT','Polizeihubschrauberstaffel Thuringen',10),
	 ('CHUKKA','CUK','Polo Aviation',17),
	 ('POOLEX','PLX','Pool Aviation',17),
	 ('PORTUGALIA','PGA','Portugalia',40),
	 ('PORTUGUESE AIR FORCE','AFP','Portuguese Air Force',40),
	 ('PORTUGUESE ARMY','POA','Portuguese Army',40),
	 ('PORTUGUESE NAVY','PON','Portuguese Navy',40),
	 ('BALLISTIC','BAT','Premiair',30),
	 ('PREMIERE','PGL','Premiair Aviation Services',17),
	 ('ADUR','PME','Premiair Fliyng Club',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('PREMIUM','PMU','Premium Aviation',10),
	 ('PRIMAVIA','PMM','Primair',43),
	 ('CARRIERS','CRY','Primavia Limited',17),
	 ('PRIVATAIR','PTI','Privatair',8),
	 ('PRIVATE WINGS','PWF','Private Wings Flugcharter',10),
	 ('PRIVILEGE','PVG','Privilege Style L',13),
	 ('VOLARE','PVL','Professione VOlare',26),
	 ('PROTEUS','PTH','Proteus Helicopteres',16),
	 ('PRONTO','PRP','PRT Aviation',13),
	 ('PSKOVAVIA','PSW','Pskovavia',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('KING STAR','KST','PTL Luftfahrtunternehemen',10),
	 ('PUBLIVOO','PUV','Publivoo',40),
	 (NULL,'PGH','Pulkovo Aircraft Services',43),
	 ('MANGO','MGO','Punto Fa',13),
	 ('DAGOBERT','QAJ','Quick Air Jet Charter',10),
	 ('QUICK','QAH','Quick Airways Holland',37),
	 ('RABBIT','RBB','Rabbit-Air',8),
	 (NULL,'BKH','RAF Barkston Heath',17),
	 ('LEUCHARS','LCS','RAF Leuchars',17),
	 ('SCAMPTON','SMZ','RAF Scampton',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SAINT ATHAN','STN','RAF St Athan',17),
	 (NULL,'SMG','RAF St Mawgan Search and Rescue',17),
	 ('TOPCLIFFE','TOF','RAF Topcliffe Flying Training Unit',17),
	 ('ANGLESEY','VYT','RAF Valley Flying Training Unit',17),
	 (NULL,'VLL','RAF Valley SAR Training Unit',17),
	 ('MITAVIA','MTL','RAF-Avia',31),
	 ('Rainbow Air','RUE','Rainbow Air Euro',17),
	 ('RANGEMILE','RGM','Rangemile Limited',17),
	 ('RATH AVIATION','RAQ','Rath Aviaton',3),
	 ('RAVEN','RVR','Raven Air',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('NEWPIN','RCJ','Raytheon Corporate Jets',17),
	 ('BALEARES','RCB','Real Aero Club De Baleares',13),
	 ('AEROREUS','CDT','Real Aero Club de Reus-Costa Dorado',13),
	 ('AEROCLUB','RCD','Real Aeroclub De Ternerife',13),
	 ('REBUS','REB','Rebus',6),
	 ('RED ARROWS','SAK','Red Arrows Display Squadron',17),
	 ('PASSION','PSH','Red Aviation',17),
	 ('RED DEVILS','DEV','Red Devils Parachute Display Team',17),
	 ('REDAIR','RHC','Redhill Aviation',17),
	 ('REED AVIATION','RAV','Reed Aviation',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('GERMAN LINK','RAG','Regio Air',10),
	 ('REGIONAL EUROPE','RAE','R�gional',16),
	 ('REGIONAL WINGS','REW','Regional Air Express',10),
	 (NULL,'N78','Regional Air Iceland',25),
	 ('GEODATA','JJM','Regional Geodata Air',13),
	 ('RELIEF','RTS','Relief Transport Services',17),
	 ('RENAN','RAN','Renan',33),
	 ('Rexair','RXR','REXAIR VIRTUEL',16),
	 ('Rheintal','RTL','Rheintalflug',3),
	 ('SPORT CLUB','RAK','Riga Airclub',31);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'POL','Rikspolisstyrelsen',44),
	 ('RIVNE UNIVERSAL','UNR','Rivne Universal Avia',48),
	 ('Sherwood','RHA','Robin Hood Aviation',3),
	 ('ROLLRIGHT','RRZ','Rollright Aviation',17),
	 ('MERLIN','RRL','Rolls-Royce Limited',17),
	 ('ROLLS','BTU','Rolls-Royce plc',17),
	 ('ROMAF','ROF','Romanian Air Force',41),
	 ('AEROMAVIA','RMV','Romavia',41),
	 ('ROSBALT','RNB','Rosneft-Baltika',43),
	 ('CATCHER','ROS','Rossair Europe',37);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('PULKOVO','SDM','Rossiya-Russian Airlines',43),
	 ('ROCKET','RKT','Rotormotion',17),
	 ('ROTTERDAM JETCENTER','JCR','Rotterdam Jet Center',37),
	 ('RAFAIR','RFR','Royal Air Force',17),
	 ('AIR CADET','ACW','Royal Air Force',17),
	 ('ASCOT','RRR','Royal Air Force',17),
	 ('KITTY','RRF','Royal Air Force',17),
	 ('VORTEX','SHF','Royal Air Force',17),
	 (NULL,'ROB','ROYAL BRITAIN',17),
	 (NULL,'DME','Royal Flight',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('NAVY','NVY','Royal Navy',17),
	 ('NETHERLANDS NAVY','NRN','Royal Netherland Navy',37),
	 ('NETHERLANDS AIR FORCE','NAF','Royal Netherlands Air Force',37),
	 ('NORWEGIAN','NOW','Royal Norwegian Air Force',38),
	 (NULL,'ARP','RPA-Aviataxi Ltd.',43),
	 ('RUBYSTAR','RSB','Rubystar',7),
	 (NULL,'RUR','Rusaero',43),
	 (NULL,'KLE','Rusaero',43),
	 ('CGI-RUSAIR','CGI','Rusair JSAC',43),
	 (NULL,'RUH','Rusich-T',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'RSJ','RusJet',43),
	 ('RUSLINE AIR','RLU','Rusline',43),
	 ('STATE AERO','RSD','Russia State Transport',43),
	 ('MIG AVIA','MIG','Russian Aircraft Corporation-MiG',43),
	 ('RUSSIAN AIRFORCE','RFF','Russian Federation Air Force',43),
	 ('RADUGA','ESL','Russian Sky Airlines',43),
	 (NULL,'KRY','Russkie Krylya',43),
	 ('ROSTUERTOL','RUZ','Rusuertol',43),
	 ('RUTLAND','RND','Rutland Aviation',17),
	 ('RHEINTRAINER','RWL','RWL Luftfahrtgesellschaft',10);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('RYANAIR','RYR','Ryanair',23),
	 ('RYAZAN AIR','RYZ','Ryazan State Air Enterprise',43),
	 ('TIRIAC AIR','TIH','S C Ion Tiriac',41),
	 ('S-AIRLINES','RLS','S-Air',43),
	 ('SIBERIAN AIRLINES','SBI','S7 Airlines',43),
	 ('TARGET','TGT','SAAB Nyge Aero',44),
	 ('SAAB-CRAFT','SCT','SAAB-Aircraft',44),
	 ('SAESA','SSS','SAESA',13),
	 ('SAGOLAIR','SGP','Sagolair Transportes Ejecutivos',13),
	 ('BLACK FIN','SBU','Saint Barth Commuter',16);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SATAIR','SHU','Sakhalinskie Aviatrassy (SAT)',43),
	 ('BERYOZA','BRZ','Samara Airlines',43),
	 ('SAMSON','SHL','Samson Aviation',17),
	 ('SARATOV AIR','SOV','Saratov Aviation Division',43),
	 ('SARK','JIM','Sark International Airways',17),
	 ('SCANOR','CNO','SAS Braathens',38),
	 ('SATA','SAT','SATA Air Acores',40),
	 ('AIR AZORES','RZO','SATA International',40),
	 ('SCANDINAVIAN','SAS','Scandinavian Airlines System',44),
	 ('ROMANIAN ACADEMY','RFT','Scoala Superioara De Aviatie Civila',41);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SUCKLING','SAY','ScotAirways',17),
	 ('SKYWORK','SKO','Scottish Airways Flyers',17),
	 ('SEAGLE','CGL','Seagle Air',46),
	 (NULL,'SRG','Search and Rescue 202',17),
	 (NULL,'SRD','Search and Rescue 22',17),
	 ('PYSHMA','UKU','Second Sverdlovsk Air Enterprise',43),
	 ('SEFA','SFA','SEFA',16),
	 ('STELLAVIA','STJ','Sella Aviation',37),
	 ('SEMITRANS','STE','Semitool Europe',17),
	 ('SENATOR','SNA','Senator Aviation Charter',10);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('CARGOPRESS','SEV','Serair Transworld Press',13),
	 (NULL,'SA1','Serbian Airlines',42),
	 ('SAF','SHP','Service Aerien Francais',16),
	 (NULL,'SPX','Service People Gesselschaft fur Charter und Service',10),
	 ('ARCOS','SDH','Servicio De Helicopteros',13),
	 ('DAKOY','DKY','Servicios Aereos Elite',13),
	 ('FLYANT','FYA','Servicios Aereos Integrales / Flyant',13),
	 ('SERVISAIR','SGH','Servisair',17),
	 ('SERVIZI AEREI','SNM','Servizi Aerei',26),
	 ('SEVAVIA','SVL','Sevastopol-Avia',48);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SIERRA SERVICES','SVT','Seven Four Eight Air Services',30),
	 ('SEVERSTAL','SSF','Severstal',43),
	 ('SHANS AIR','SNF','Shans Air',43),
	 ('SHARINK','UGP','Shar Ink',43),
	 ('SHAWBURY','SYS','Shawbury Flying Training Unit',17),
	 ('SHELL','SHE','Shell Aircraft',17),
	 (NULL,'SHO','Sheremetyevo-Cargo',43),
	 ('SHOP AIR','SHG','Shoprite Group',17),
	 ('WAY AERO','SWW','Shovkoviy Shlyah',48),
	 ('SIBAVIA','SIB','Sibaviatrans',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AIR SILESIA','SUA','Silesia Air',9),
	 ('SILVERLINE','SLD','Silver Air',9),
	 ('ENVOY','FJE','Silverjet',17),
	 ('SINCOM AVIA','INK','Sincom-Avia',48),
	 ('SIRAIR','SRN','Sirair',43),
	 ('SIRIO','SIO','Sirio',26),
	 ('SIRIO EXECUTIVE','SIW','Sirio Executive',26),
	 ('SIRIUS AERO','CIG','Sirius-Aero',43),
	 (NULL,'SIT','SITA',5),
	 ('SKIF-AIR','USK','Skif-Air',48);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('AIR SKORPIO','SPN','Skorpion Air',6),
	 ('SIGMA','SGM','Sky Aircraft Service',37),
	 ('SKYCAM','SCK','Sky Cam',16),
	 ('MATRA','HSK','Sky Europe Airlines',46),
	 ('AIR CRETE','SEH','Sky Express',20),
	 ('EXPRESS SKY','SXP','Sky Express',39),
	 ('SKYSTORM','SXR','Sky Express',43),
	 ('HELISKY','HSY','Sky Helicopteros',13),
	 ('SWISSLINK','SWY','Sky Jet',8),
	 ('SKY SERVICE','SKS','Sky Service',5);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'GSW','Sky Wings Airlines',20),
	 ('SKYFOX','SRK','Sky Work Airlines',8),
	 ('SKY AIROPS','KYB','Skybridge Airops',26),
	 ('SKYDRIFT','SDL','Skydrift',17),
	 ('RELAX','ESK','SkyEurope',46),
	 ('SKYGATE','SGT','Skygate',37),
	 ('SKYKING','SKI','Skyking',17),
	 ('BLUEJET','SIH','Skynet Airlines',23),
	 ('HELIRIM','HRI','Skyraidybos Mokymo Centras',29),
	 ('IGUANA','IGA','Skytaxi',39);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SKY EXPRESS','SKX','Skyways Express',44),
	 ('SLOANE','SLN','Sloane Aviation',17),
	 ('SLOVAK AIRFORCE','SQF','Slovak Air Force',46),
	 ('SLOV LINE','SLL','Slovak Airlines',46),
	 ('SLOVAK GOVERNMENT','SSG','Slovak Government Flying Service',46),
	 ('SLOVAK AEROCLUB','SQA','Slovak National Aeroclub',46),
	 ('SLOVENIAN','SIV','Slovenian Armed Forces',45),
	 ('GORDON','SMF','Smalandsflyg',44),
	 (NULL,'ELC','Small Planet Airlines',29),
	 (NULL,'SBD','Snowbird Airlines',14);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SLOW FROG','KOL','SOCHI AIR',43),
	 ('russian doll','QER','SOCHI AIR CHATER',43),
	 ('ADLER EXPRESS','SAE','SOCHI AIR EXPRESS',43),
	 ('SOKO AIR','OKT','Soko Aviation',13),
	 ('AEROSOKOL','PIV','Sokol',43),
	 ('SAINTS','SFU','Solent Flight',17),
	 ('SOLINAIR','SOP','Solinair',45),
	 ('SOLO','OLO','Soloflight',17),
	 ('SONNIG','ONG','Sonnig SA',8),
	 ('MEDICAL AIR','SAG','SOS Flygambulans',44);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('MEDICOPTER','MCG','SOS Helikoptern Gotland',44),
	 ('SOUTHLINE','OTL','South Airlines',48),
	 ('SOUTHCOAST','GAD','South Coast Aviation',17),
	 (NULL,'SOC','Southern Cargo Air Lines',43),
	 ('SPANAIR','JKK','Spanair',13),
	 ('AIRMIL','AME','Spanish Air Force',13),
	 (NULL,'BXS','Spantax S.A.',13),
	 ('SPARK','BVV','Spark+ Joint-Stock Company',43),
	 ('SALDUERO','SPS','SPASA',13),
	 ('AVIASPEC','BHV','Specavia Air Company',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('DOPE','SSO','Special Scope Limited',17),
	 ('SPECSAVERS','SSZ','Specsavers Aviation',17),
	 ('AIR TONY','LSP','Spectrum Aviation Incorporated',17),
	 ('SPEEDWING','SPW','Speedwings',8),
	 (NULL,'SRN','Sprintair',39),
	 ('STAC','SGF','STAC Swiss Government Flights',8),
	 ('STADIUM','STC','Stadium City Limited',17),
	 ('STAPLEFORD','STL','Stapleford Flight Centre',17),
	 ('WHITESTAR','SRR','Star Air',11),
	 ('STAR','STA','Star Aviation',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('STAR SERVICE','SSD','Star Service International',16),
	 ('STAR WORK','SWP','Star Work Sky',26),
	 ('STARDUST','GXL','Star XL German Airlines',10),
	 (NULL,'HCW','Star1 Airlines',29),
	 ('BLARNEY','BLY','Starair',23),
	 ('ELISTARFLY','SLF','Starfly',26),
	 ('STARLING','STS','Starling Airlines Spain',13),
	 ('STARSPEED','SSP','Starspeed',17),
	 ('FLIGHT ACADEMY','UFA','State Flight Academy of Ukraine',48),
	 ('SUMES','SUM','State Unitary Air Enterprise',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('STATUS-ALPHA','STB','Status-Alpha Airline',48),
	 ('STERLING','SNB','Sterling Airlines',11),
	 ('SILVER','SVH','Sterling Helicopters',17),
	 ('SMART','VGS','Stichting Vliegschool 16Hoven',37),
	 ('STREAMLINE','SSW','Streamline Aviation',17),
	 ('SLOPS','STO','Streamline Ops',43),
	 ('FIRST FLIGHT','FFD','Stuttgarter Flugdienst',10),
	 ('STYRIAN','STY','Styrian Airways',3),
	 ('SUD LINES','SDU','Sud Airlines',16),
	 ('SU-CRAFT','SDB','Sukhoi Design Bureau Company',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SUNSCAN','SUS','Sun Air of Scandinavia',11),
	 ('MIDNIGHT','MDT','Sundt Air',38),
	 ('HIGHSWEDE','HSV','Svenska Direktflyg',44),
	 ('RussianConnecty','SJM','Svyaz Rossiya',43),
	 ('FLYING SWEDE','SWV','Swe Fly',44),
	 ('SWEDELINE','SWE','Swedeways',44),
	 ('SWEDISH','CFL','Swedish Airlines',44),
	 ('SWEDEFORCE','SVF','Swedish Armed Forces',44),
	 ('CALIBRATION','CBN','Swedish Civil Aviation Administration',44),
	 ('BLACKBIRD','BBB','SwedJet Airways',44);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('Starline','SRL','Swedline Express',44),
	 ('SWIFTCOPTERS','WFC','Swift Copters',8),
	 ('SWIFT','SWT','Swiftair',13),
	 ('SWISS AIR FORCE','SUI','Swiss Air Force',8),
	 ('SWISS AMBULANCE','SAZ','Swiss Air-Ambulance',8),
	 ('SWISS EAGLE','EAB','Swiss Eagle',8),
	 ('EUROSWISS','SWU','Swiss European Air Lines',8),
	 ('SWISS','SWR','Swiss International Air Lines',8),
	 ('SWISS JET','SJT','Swiss Jet',8),
	 ('Swissair','SWR','Swissair',8);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SWISSBOOGIE','SWB','Swissboogie Parapro',8),
	 ('SYNERGY','SYG','Synergy Aviation',17),
	 ('CABOVERDE','TCV','TACV',40),
	 ('TADAIR','TDC','Tadair',13),
	 ('HELITAF','HET','TAF Helicopters',13),
	 ('TAG AVIATION','FPG','TAG Aviation',8),
	 ('TAG ESPANA','TGM','TAG Aviation Espana',13),
	 ('SOVEREIGN','VIP','Tag Aviation UK',17),
	 (NULL,'FBO','TAG Farnborough Airport',17),
	 ('ISLAND BIRD','TKE','Take Air Line',16);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('TANDEM','TDM','Tandem Aero',33),
	 ('HELI TANGO','HTO','Tango Bravo',16),
	 ('AIR PORTUGAL','TAP','TAP Portugal',40),
	 ('TAROM','ROT','Tarom',41),
	 ('TATARSTAN','TAK','Tatarstan Airlines',43),
	 ('Taunusair','TAQ','Taunus Air Gmbh',10),
	 ('TAVREY','TVR','Tavrey Airlines',48),
	 ('TAXI JET','TRF','Taxi Air Fret',16),
	 ('TAYFLITE','TYF','Tayflite',17),
	 ('TAYSIDE','TFY','Tayside Aviation',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('Teamline','TLW','Teamline Air',3),
	 ('TECHMONT','TEM','Tech-Mont Helicopter Company',46),
	 ('TECFOTO','TEF','Tecnicas Fotograficas',13),
	 ('DOT TEL','DOT','Telnic Limited',17),
	 ('TEPAVIA','TET','Tepavia-Trans Airlines',33),
	 ('TESIS','TIS','Tesis',43),
	 ('THANET','TGC','TG Aviation',17),
	 ('GRIFFON','GFN','The 955 Preservation Group',17),
	 ('THOMAS COOK','TCW','Thomas Cook Airlines',5),
	 ('KESTREL','TCX','Thomas Cook Airlines',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('TOMSON','TOM','Thomsonfly',17),
	 (NULL,'IHS','Thryluthjonustan',25),
	 ('BLUELINE','BLI','Thyssen Krupp AG',10),
	 ('MOTH','MOH','Tigerfly',17),
	 ('TIME AIR','TIE','Time Air',9),
	 ('BOX','BOX','Tiphook PLC',17),
	 ('TIRAMAVIA','TVI','Tiramavia',33),
	 ('ZAP','AWC','Titan Airways',17),
	 ('QUALITY','TAY','TNT Airways',5),
	 ('NITRO','NTR','TNT International Aviation',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('T&','T&O','Tom''s & co airliners',16),
	 (NULL,'TKS','Tomsk-Avia',43),
	 ('TOP SPEED','TPD','Top Speed',3),
	 ('TOPFLY','TLY','Top-Fly',13),
	 ('TOURAINE HELICO','THF','Touraine Helicoptere',16),
	 ('TASA','TGE','Trabajos Aereos',13),
	 ('PIJO','AIM','Trabajos Aereos Murcianos',13),
	 ('TRAVASA','TVH','Trabajos Aereos Vascongados',13),
	 ('TRADEAIR','TDR','Trade Air',21),
	 (NULL,'TRG','TRAGSA (Medios Aereos)',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('HIGH TIDE','TRJ','Trans Euro Air',17),
	 ('LYON HELIJET','THZ','Trans Helicoptere Service',16),
	 ('TRANSJET','SWL','Trans Jet Airways',44),
	 ('TRANS-KIEV','KCA','Trans-Kiev',48),
	 ('TRANSOVIET','TSO','Transaero Airlines',43),
	 ('AIRTRAF','TSA','Transair France',16),
	 ('KOTAIR','KTS','Transair-Gyraintiee',43),
	 (NULL,'TDK','Transavia Denmark',11),
	 ('FRENCH SUN','TVF','Transavia France',16),
	 ('TRANSAVIA','TRA','Transavia Holland',37);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('TRANSBALTIKA','KTB','Transaviabaltika',29),
	 ('TRANSEXPORT','TXC','Transaviaexport',7),
	 ('TRANS-BALLERIO','TVO','Transavio',26),
	 ('TRANSCORP','TCP','Transcorp Airways',17),
	 ('TRANSEURLINE','TEP','Transeuropean Airlines',43),
	 (NULL,'TNS','Transilvania',41),
	 ('TRANSAIR EXPRESS','TXE','Transilvania Express',41),
	 ('TRANSLIFT','TLA','Translift Airways',23),
	 ('TRANSPED','TNP','Transped Aviation',3),
	 ('TRANSPORTAIR','TSI','Transport''air',16);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'RGG','TransRussiaAirlines',43),
	 ('TRANSWEDE','TWE','Transwede Airways',44),
	 ('SWISSTRANS','TSW','Transwings',8),
	 ('SKYTRAVEL','TVS','Travel Service',9),
	 ('TRAVEL SERVICE','TVL','Travel Service',22),
	 ('TRAVELAIR','TAX','Travelair',10),
	 ('TRAINER','TNX','Trener Ltd',22),
	 ('CAROLUS','CLU','Triple Alpha',10),
	 ('TROPIC','TSV','Tropair Airservices',17),
	 ('TRYGG','TYG','Trygg-Flyg',44);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('PROGRESS','PSS','TSSKB-Progress',43),
	 ('BEAUTY','TUB','TUI Airlines Belgium',5),
	 ('YELLOW CAB','HLX','TUIfly',10),
	 ('BLUESCAN','BLX','TUIfly Nordic',44),
	 ('URSAL','TUL','Tulpar Air',43),
	 ('TUNA','TUZ','Tuna Aero',44),
	 (NULL,'TBC','Turbine Air Cargo UK',17),
	 ('COLIBRI','TWO','Twente Airlines',37),
	 ('TWINJET','TJT','Twin Jet',16),
	 (NULL,'TWJ','Twinjet Aircraft Sales',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('TYROL AMBULANCE','TYW','Tyrol Air Ambulance',3),
	 ('TYROLEAN','TYR','Tyrolean Airways',3),
	 ('TYROLJET','TJS','Tyrolean Jet Service',3),
	 ('TUMTEL','TUM','Tyumenspecavia',43),
	 ('UCOAVIACION','UCO','Ucoaviacion',13),
	 ('AVIASYSTEM','UES','Ues-Avia Aircompany',48),
	 ('HELIMED','HLE','UK HEMS',17),
	 ('KHALIQ','UKI','UK International Airlines',17),
	 ('LEOPARD','LPD','UK Royal/HRH Duke of York',17),
	 ('UKRAINE ALLIANCE','UKL','Ukraine Air Alliance',48);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('ENTERPRISE UKRAINE','UKN','Ukraine Air Enterprise',48),
	 (NULL,'UAT','Ukraine Atlantic',48),
	 ('UKRAINE INTERNATIONAL','AUI','Ukraine International Airlines',48),
	 ('KIROVTRANS','TRB','Ukraine Transavia',48),
	 ('CARGOTRANS','UKS','Ukrainian Cargo Airways',48),
	 ('UKRAINE COPTERS','UHL','Ukrainian Helicopters',48),
	 ('PILOT SCHOOL','UPL','Ukrainian Pilot School',48),
	 ('AIRRUH','UTS','Ukrainian State Air Traffic Service Enterprise',48),
	 ('PILOT AIR','UHS','Ulyanovsk Higher Civil Aviation School',43),
	 ('UKRAINE MEDITERRANEE','UKM','UM Airlines',48);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('UNICOPTER','UNC','Uni-Fly',11),
	 ('UNIEURO','UNU','Unifly Servizi Aerei',26),
	 ('LEADAIR','LEA','Unijet',16),
	 ('UNISERVE','SAU','United Aviation Services',13),
	 ('EXAM','EXM','United Kingdom Civil Aviation Authority',17),
	 ('MINAIR','CFU','United Kingdom Civil Aviation Authority',17),
	 ('STANDARDS','SDS','United Kingdom Civil Aviation Authority',17),
	 ('POLICE','UKP','United Kingdom Home Office',17),
	 ('SPARROWHAWK','KRH','United Kingdom Royal VIP Flight',17),
	 ('KITTYHAWK','KRF','United Kingdom Royal VIP Flights',17);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('RAINBOW','TQF','United Kingdom Royal VIP Flights',17),
	 ('TOPAZ','UMS','Unitemp-M',43),
	 ('KHARKIV UNIVERSAL','HBU','Universal Avia',48),
	 ('PROJET','UNJ','Universal Jet',13),
	 (NULL,'UAD','University Air Squadron',17),
	 (NULL,'UAJ','University Air Squadron',17),
	 (NULL,'UAA','University Air Squadron',17),
	 (NULL,'UAH','University Air Squadron',17),
	 ('UAY','UAY','University of Birmingham Air Squadron (RAF)',17),
	 ('URAI','URV','Uraiavia',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('SVERDLOVSK AIR','SVR','Ural Airlines',43),
	 ('URGEMER','UGC','Urgemer Canarias',13),
	 ('UTAIR','UTA','UTair Aviation',43),
	 ('VEEBEE','VBA','V Bird Airlines Netherlands',37),
	 ('VEE-AVIA','WIW','V-avia Airline',48),
	 ('ROADWATCH','RDW','Valair AG (Helicoptere)',8),
	 ('VALAN','VLN','Valan Limited',33),
	 ('ROTOR','EHR','Valfell-Verkflug',25),
	 ('EUROVAN','VAA','Van Air Europe',9),
	 ('WEGA FRANKO','WGA','Vega Air Company',48);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('VEGA AIRLINES','VEA','Vega Airlines',6),
	 ('NET RAIL','BTP','Veritair Ltd',17),
	 ('NIGHT RIDER','GRV','Vernicos Aviation',20),
	 ('VERITAIR','VRA','Vertair',17),
	 ('VERTICAL','VLT','Vertical-T Air Company',43),
	 ('VETERAN','VPB','Veteran Air',48),
	 ('Nico','FVG','VG Airlines (IV)',5),
	 ('EARLY BIRD','VHM','VHM Schul-und-Charterflug',10),
	 ('VIAGGIO','VOA','Viaggio Air',6),
	 ('VITUS','VIB','Vibroair Flugservice',10);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('VICHI','VIH','Vichi',33),
	 ('VICKERS','VSB','Vickers Limited',17),
	 ('Vickjet','VKJ','VickJet',16),
	 ('VICTOR ECHO','VEE','Victor Echo',13),
	 ('ENDEAVOUR','ENV','Victoria Aviation',17),
	 ('VIENNA FLIGHT','VIF','VIF Luftahrt',3),
	 ('SWEDJET','VIK','Viking Airlines',44),
	 ('DELPHI','VKH','Viking Hellas',20),
	 ('MOV AIR','MOV','VIM Airlines',43),
	 (NULL,'MVY','VIM-Aviaservice',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('VINAIR','VIN','Vinair - Helicoptereos',40),
	 ('VIP TAXI','VPA','VIP Air',46),
	 ('PAREX','PRX','VIP Avia',31),
	 (NULL,'VNK','Vipport Joint Stock Company',43),
	 ('VIRGIN','VIR','Virgin Atlantic Airways',17),
	 ('VIRGIN EXPRESS','VEX','Virgin Express',5),
	 ('GREEN ISLE','VEI','Virgin Express Ireland',23),
	 (NULL,'VWA','Virginwings',10),
	 ('VISIG','VSG','Visig Operaciones Aereas',13),
	 ('VISIONAIR','VAT','Visionair',23);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('VLADAIR','VLK','Vladivostok Air',43),
	 ('RUBENS','VLM','VLM Airlines',5),
	 ('VOINTEH','VTV','Vointeh',6),
	 ('VOLA','VLE','Volare Airlines',26),
	 ('UKRAINE VOLARE','VRE','Volare Airlines',48),
	 ('GOUMRAK','WLG','Volga Aviaexpress',43),
	 ('VOLGA-DNEPR','VDA','Volga-Dnepr Airlines',43),
	 ('VOLOGDA AIR','VGV','Vologda State Air Enterprise',43),
	 ('Volotea','VOO','Volotea',13),
	 (NULL,'VOE','VOLOTEA Airways',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('VASO','VSO','Voronezh Aircraft Manufacturing Society',43),
	 ('VOSTOK','VTK','Vostok Airlines',43),
	 ('VUELING','VLG','Vueling Airlines',13),
	 (NULL,'VI4','Vuola Italia',26),
	 ('VZLYET','VZL','Vzlyet',43),
	 ('VULCAN','WAD','Waddington FTU',17),
	 ('GOTHIC','GOT','Walter I Linkoping',44),
	 ('AIRTAX','ATX','Warwickshire Aerocentre Ltd.',17),
	 ('WDL','WDL','WDL Aviation',10),
	 ('WELCOMEAIR','WLC','Welcome Air',3);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('BLUESTAR','BLW','Wermlandsflyg AB',44),
	 ('WEST LUX','WLX','West Air Luxembourg',30),
	 ('AIR SWEDEN','SWN','West Air Sweden',44),
	 ('TEEBIRD','TEE','West Freugh DTEO',17),
	 (NULL,'WFX','Westfalia Express VA',10),
	 ('WEST LINE','WSL','Westflight Aviation',17),
	 ('WESTLAND','WHE','Westland Helicopters',17),
	 ('YOUNG SKY','WHT','White',40),
	 ('WHITE EAGLE','WEA','White Eagle Aviation',39),
	 ('WIDEROE','WIF','Wider�e',38);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('WEEKING','WHS','Wiking Helikopter Service',10),
	 ('GRAND PRIX','WGP','Williams Grand Prix Engineering',17),
	 ('GHIBLI','JET','Wind Jet',26),
	 ('WIND ROSE','WRC','Wind Rose Aviation',48),
	 ('QUADRIGA','QGA','Windrose Air',10),
	 ('STRIKER','WIT','Wittering FTU',17),
	 ('WIZZ AIR','WZZ','Wizz Air',22),
	 ('WIZZBUL','WVL','Wizz Air Hungary',6),
	 ('WIZZAIR UKRAINE','WAU','Wizz Air Ukraine',48),
	 ('WONDAIR','WNR','Wondair on Demand Aviation',13);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 ('CAUSEWAY','CWY','Woodgate Executive Air Charter',17),
	 ('WYCOMBE','WYC','Wycombe Air Centre',17),
	 ('EXCLUSIVE JET','XJC','Xclusive Jet Charter Limited',17),
	 ('XRAY','XJT','Xjet Limited',17),
	 ('STARWAY','SEU','XL Airways France',16),
	 ('XP PARCEL','XPS','XP Internation',37),
	 ('XPTO','XPT','XPTO',40),
	 ('YAK-SERVICE','AKY','Yak-Service',43),
	 ('YAK AVIA','YAK','Yakolev',43),
	 ('YAMAL','LLM','Yamal Airlines',43);
INSERT INTO public.airlines (call_sign,icao,"name",country_id) VALUES
	 (NULL,'YEP','YES Airways',39),
	 ('YUZMASH','UMK','Yuzhmashavia',48),
	 ('BAIKAL ','ZTT','ZABAIKAL AIRLINES',43),
	 ('Lakeair','ZZZ','Zabaykalskii Airlines',43),
	 (NULL,'PZY','Zapolyarie Airlines',43),
	 ('ZIMEX','IMX','Zimex Aviation',8),
	 ('ZOREX','ORZ','Zorex',13),
	 ('MALI LOSINJ','MLU','Zracno Pristaniste Mali Losinj',21);